### ISSUE TITLE
ValueError in DQN

### ISSUE THREAD

**Issue by JamesChuanggg** [ppwwyyxx/tensorpack#108]
Hi,

Thanks for sharing such an awesome toolbox.
However while I'm running DQN without modifying by 
```
./DQN.py --rom breakout.bin
```
Following error message occured,
```
Traceback (most recent call last):
  File "./DQN.py", line 228, in <module>
    QueueInputTrainer(config).train()
  File "/data/VSLab/james847286/Work/ITRI/tensorpack/tensorpack/train/base.py", line 58, in train
    self.setup()
  File "/data/VSLab/james847286/Work/ITRI/tensorpack/tensorpack/train/base.py", line 130, in setup
    self._setup()
  File "/data/VSLab/james847286/Work/ITRI/tensorpack/tensorpack/train/feedfree.py", line 106, in _setup
    summary_moving_average(), name='train_op')
  File "/data/VSLab/james847286/.local/lib/python2.7/site-packages/functools32/functools32.py", line 378, in wrapper
    result = user_function(*args, **kwds)
  File "/data/VSLab/james847286/Work/ITRI/tensorpack/tensorpack/tfutils/summary.py", line 140, in summary_moving_average
    avg_maintain_op = averager.apply(tensors)
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/data/VSLab/james847286/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable predict_reward/EMA/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

It seems that the variable accidentally being set to reuse in certain variable scope. Any idea?

**Comment by ppwwyyxx** [comment]
Thanks for reporting!
