### ISSUE TITLE
ImportError: No module named freeze

### ISSUE THREAD

**Issue by nesciemus** [ppwwyyxx/tensorpack#114]
Why did I get ImportError: No module named freeze when try to import the tensorpack?

**Comment by ppwwyyxx** [comment]
Can you post your logs in detail?

**Comment by nesciemus** [comment]
$ python mnist-convnet.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "mnist-convnet.py", line 19, in <module>
    from tensorpack import *
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/__init__.py", line 8, in <module>
    from tensorpack.train import *
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/train/__init__.py", line 29, in <module>
    global_import(module_name)
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/train/__init__.py", line 13, in global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/train/base.py", line 13, in <module>
    from .config import TrainConfig
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/train/config.py", line 7, in <module>
    from ..callbacks.group import Callbacks
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/callbacks/__init__.py", line 28, in <module>
    _global_import(module_name)
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/callbacks/__init__.py", line 13, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/callbacks/inference_runner.py", line 11, in <module>
    from ..dataflow import DataFlow
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/dataflow/__init__.py", line 29, in <module>
    _global_import(module_name)
  File "/home/yangchen/projects/work/binarized/tensorpack/tensorpack/dataflow/__init__.py", line 16, in _global_import
    p = __import__(name, globals(), locals(), level=1)
ImportError: No module named freeze



I see there is no dependency for freeze.
And it gives the same error even I installed the freeze package.

**Comment by ppwwyyxx** [comment]
The [CI](https://travis-ci.org/ppwwyyxx/tensorpack) can import tensorpack, so it's not likely to be a problem of the code.

Do you happen to have a file called freeze.pyc somewhere? (e.g. in tensorpack/dataflow/).

**Comment by nesciemus** [comment]
I see why.
Because I have installed the dataset package (a database interface package) before and there is a naming conflict.

**Comment by ppwwyyxx** [comment]
I see. I'll have to write it differently to avoid importing some external packages by mistake. Thanks for finding it out.
