### ISSUE TITLE
Training on DQN breakout game

### ISSUE THREAD

**Issue by babanhuihui** [ppwwyyxx/tensorpack#118]
Hi, I was trying to use DQN to train breakout by "./DQN.py --rom breakout.bin". However, I encountered following error. Could you please hint me how to deal with this?

Thanks.

[0125 00:42:23 @stats.py:101] param-summary/fc0/W-rms: 0.018247
[0125 00:42:23 @stats.py:101] param-summary/fct/W-rms: 0.054118
[0125 00:42:23 @stats.py:101] predict_reward: -0.095098
[0125 00:42:23 @base.py:182] Start Epoch 2 ...
100%|#########################################################################################################|10000/10000[32:17<00:00, 5.17it/s]
[0125 01:14:41 @base.py:194] Epoch 2 (global_step 20000) finished, time:1937.52 sec.
[0125 01:14:41 @saver.py:80] Model saved to train_log/DQN/model-20000.
[0125 01:14:41 @expreplay.py:204] Exploration changed to 0.98
[0125 01:14:41 @stats.py:101] SummaryGradient/conv0/W/rms: 1.7831e-05
[0125 01:14:41 @stats.py:101] SummaryGradient/conv0/alpha/rms: 0.0011199
[0125 01:14:41 @stats.py:101] SummaryGradient/conv0/b/rms: 0.00013539
[0125 01:14:41 @stats.py:101] SummaryGradient/conv1/W/rms: 7.2933e-06
[0125 01:14:41 @stats.py:101] SummaryGradient/conv1/alpha/rms: 0.00094099
[0125 01:14:41 @stats.py:101] SummaryGradient/conv1/b/rms: 0.00022113
[0125 01:14:41 @stats.py:101] SummaryGradient/conv2/W/rms: 8.8745e-06
[0125 01:14:41 @stats.py:101] SummaryGradient/conv2/alpha/rms: 0.0056876
[0125 01:14:41 @stats.py:101] SummaryGradient/conv2/b/rms: 0.0001549
[0125 01:14:41 @stats.py:101] SummaryGradient/conv3/W/rms: 4.5882e-06
[0125 01:14:41 @stats.py:101] SummaryGradient/conv3/alpha/rms: 0.00083669
[0125 01:14:41 @stats.py:101] SummaryGradient/conv3/b/rms: 0.00063492
[0125 01:14:41 @stats.py:101] SummaryGradient/fc0/W/rms: 1.9919e-06
[0125 01:14:41 @stats.py:101] SummaryGradient/fc0/b/rms: 0.00011362
[0125 01:14:41 @stats.py:101] SummaryGradient/fct/W/rms: 0.00010893
[0125 01:14:41 @stats.py:101] SummaryGradient/fct/b/rms: 0.0046374
[0125 01:14:41 @stats.py:101] cost: 0.0032585
[0125 01:14:41 @stats.py:101] expreplay/max_score: 9
[0125 01:14:41 @stats.py:101] expreplay/mean_score: 0.94271
[0125 01:14:41 @stats.py:101] input_queue_size: 50
[0125 01:14:41 @stats.py:101] learning_rate: 0.001
[0125 01:14:41 @stats.py:101] param-summary/conv0/W-rms: 0.13747
[0125 01:14:41 @stats.py:101] param-summary/conv1/W-rms: 0.050279
[0125 01:14:42 @stats.py:101] param-summary/conv2/W-rms: 0.06357
[0125 01:14:42 @stats.py:101] param-summary/conv3/W-rms: 0.061343
[0125 01:14:42 @stats.py:101] param-summary/fc0/W-rms: 0.018249
[0125 01:14:42 @stats.py:101] param-summary/fct/W-rms: 0.054057
[0125 01:14:42 @stats.py:101] predict_reward: -0.053162
[0125 01:14:42 @base.py:182] Start Epoch 3 ...
100%|#########################################################################################################|10000/10000[32:17<00:00, 5.17it/s]
[0125 01:46:59 @base.py:194] Epoch 3 (global_step 30000) finished, time:1937.74 sec.
[0125 01:47:00 @saver.py:80] Model saved to train_log/DQN/model-30000.
[0125 01:47:00 @expreplay.py:204] Exploration changed to 0.97
W tensorflow/core/kernels/queue_base.cc:294] _0_input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "./DQN.py", line 229, in <module>
[0125 01:47:00 @input_data.py:114] Enqueue Thread Exited.
    QueueInputTrainer(config).train()
  File "/home/ubuntu/tensorpack/tensorpack/train/base.py", line 65, in train
    self.main_loop()
  File "/home/ubuntu/tensorpack/tensorpack/train/base.py", line 197, in main_loop
    self.trigger_epoch()
  File "/home/ubuntu/tensorpack/tensorpack/train/base.py", line 98, in trigger_epoch
    self.config.callbacks.trigger_epoch()
  File "/home/ubuntu/tensorpack/tensorpack/callbacks/base.py", line 94, in trigger_epoch
    self._trigger_epoch()
  File "/home/ubuntu/tensorpack/tensorpack/callbacks/group.py", line 122, in _trigger_epoch
    cb.trigger_epoch()
  File "/home/ubuntu/tensorpack/tensorpack/callbacks/base.py", line 94, in trigger_epoch
    self._trigger_epoch()
  File "/home/ubuntu/tensorpack/tensorpack/callbacks/base.py", line 171, in _trigger_epoch
    self.cb.epoch_num = self.epoch_num - 1
AttributeError: can't set attribute

**Comment by ppwwyyxx** [comment]
Sorry about this. Should get fixed now.
