### ISSUE TITLE
I tried Pretrained alexnet model. But I can not.

### ISSUE THREAD

**Issue by sounansu** [ppwwyyxx/tensorpack#18]
I tried to run:
    ./alexnet-dorefa.py --load alexnet-126.npy --run a.jpg --dorefa 1,2,6

but taceback occured.

Traceback (most recent call last):
  File "./alexnet-dorefa.py", line 305, in <module>
    run_image(Model(), ParamRestore(np.load(args.load, encoding='latin1').item()), args.run)
  File "./alexnet-dorefa.py", line 256, in run_image
    meta = dataset.ILSVRCMeta()
  File "/home/sounansu/work/tensorflow/tensorpack/tensorpack/dataflow/dataset/ilsvrc.py", line 34, in __init__
    self.caffepb = get_caffe_pb()
  File "/home/sounansu/work/tensorflow/tensorpack/tensorpack/utils/loadcaffe.py", line 83, in get_caffe_pb
    proto_path = download(CAFFE_PROTO_URL, dir)
  File "/home/sounansu/work/tensorflow/tensorpack/tensorpack/utils/fs.py", line 39, in download
    logger.error("Failed to download {}".format(url))
NameError: global name 'logger' is not defined

Please advice!

**Comment by ppwwyyxx** [comment]
Fixed a missing import line in 2387c6222
Also, the error indicates that you cannot download from `https://github.com/BVLC/caffe/raw/master/src/caffe/proto/caffe.proto`, so you may need to check your network as well.

**Comment by sounansu** [comment]
Thank you.
Line 305 trace back are not occurred.

YES,YES.
I have another problem not tensorpack problem.
My network environment are under proxy network.

So, I set environment variables for proxy ,
http_proxy=http://pxoxyurl:8080/
https_proxy=https://pxoxyurl:8080/
HTTPS_PROXY=https://pxoxyurl:8080/
HTTP_PROXY=http://pxoxyurl:8080/
But, python or tensorflow can not understand these variables.....


-----------------------------------------------------------------------------
$ ./alexnet-dorefa.py --load alexnet-126.npy --run a.jpg --dorefa 1,2,6
.
.
.
[0913 10:27:26 @fs.py:40] ERR Failed to download https://github.com/BVLC/caffe/raw/master/src/caffe/proto/caffe.proto
Traceback (most recent call last):
  File "./alexnet-dorefa.py", line 303, in <module>
    run_image(Model(), ParamRestore(np.load(args.load, encoding='latin1').item()), args.run)
  File "./alexnet-dorefa.py", line 255, in run_image
    meta = dataset.ILSVRCMeta()
  File "/home/sounansu/tensorpack/tensorpack/dataflow/dataset/ilsvrc.py", line 34, in __init__
    self.caffepb = get_caffe_pb()
  File "/home/sounansu/tensorpack/tensorpack/utils/loadcaffe.py", line 83, in get_caffe_pb
    proto_path = download(CAFFE_PROTO_URL, dir)
  File "/home/sounansu/tensorpack/tensorpack/utils/fs.py", line 36, in download
    fpath, _ = urllib.request.urlretrieve(url, fpath, reporthook=_progress)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1182, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
---------------------------------------------------------------------

**Comment by ppwwyyxx** [comment]
That's a python issue, and I don't think it's related to proxy.
urllib in python definitely supports http_proxy environment variables. But it looks like there is something wrong with SSL. Googling the error would give you something you can try.

**Comment by sounansu** [comment]
I try to search urllib issue.
But current state are not good.....
(I understand, i can access not secure url, but can not access secure url,,,)

Thank you for your advises.
I continue to try.....
