### ISSUE TITLE
ImageFromFile(imgs, shuffle=True).get_data() fails

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#195]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorpack/dataflow/common.py", line 217, in get_data
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.4/dist-packages/tensorpack/dataflow/image.py", line 36, in get_data
    self.rng.shuffle(self.files)
AttributeError: 'ImageFromFile' object has no attribute 'rng'

**Comment by ppwwyyxx** [comment]
You should always call reset_state() before using a dataflow.
http://tensorpack.readthedocs.io/en/latest/tutorial/dataflow.html#reuse-in-other-frameworks
