### ISSUE TITLE
Use tfdebug when training

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#209]
I tried to use tfdebug when training image-resnet.py. To use tfdebug, I change the creation of TrainConfig as follow: 
```
    sess = SessionCreatorAdapter(NewSessionCreator(), lambda sess: tf_debug.LocalCLIDebugWrapperSession(sess))
    return TrainConfig(
        session_creator=sess,
        dataflow=dataset_train,
        callbacks=[
            ModelSaver(),
            InferenceRunner(dataset_val, [
                ClassificationError('wrong-top1', 'val-error-top1'),
                ClassificationError('wrong-top5', 'val-error-top5')]),
            ScheduledHyperParamSetter('learning_rate',
                                      [(30, 1e-2), (60, 1e-3), (85, 1e-4), (95, 1e-5)]),
            HumanHyperParamSetter('learning_rate'),
        ],
        model=Model(),
        steps_per_epoch=5000,
        max_epoch=110,
    )
```
When the training starts, I can enter the tfdebug interface and enter "run" command several times to initialize the training. But when it starts to load data and actually train, I get the following error:
```
[0327 18:50:43 @base.py:158] Start Epoch 1 ...
[0327 18:50:45 @input_data.py:118] ERR Exception in EnqueueThread:                                                                                                 |0/5000[00:00<?,?it/s]
Traceback (most recent call last):
  File "/home/jesse/tensorflow_workspace/tensorpack/tensorpack/train/input_data.py", line 114, in run
    self.op.run(feed_dict=feed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1552, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3776, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/wrappers/framework.py", line 470, in run
    run_end_resp = self.on_run_end(run_end_req)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 288, in on_run_end
    self._remove_dump_root()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 299, in _remove_dump_root
    shutil.rmtree(self._dump_root)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 416, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 414, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'tower0'
[0327 18:50:45 @input_data.py:124] EnqueueThread Exited.
2017-03-27 18:51:45.127538: E tensorflow/stream_executor/cuda/cuda_driver.cc:893] failed to allocate 3.80G (4083146240 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2017-03-27 18:51:45.142825: E tensorflow/stream_executor/cuda/cuda_driver.cc:893] failed to allocate 3.42G (3674831616 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

Traceback (most recent call last):
  File "imagenet-resnet.py", line 260, in <module>
    SyncMultiGPUTrainer(config).train()
  File "/home/jesse/tensorflow_workspace/tensorpack/tensorpack/train/base.py", line 93, in train
    self.main_loop()
  File "/home/jesse/tensorflow_workspace/tensorpack/tensorpack/train/base.py", line 163, in main_loop
    self.run_step()  # implemented by subclass
  File "/home/jesse/tensorflow_workspace/tensorpack/tensorpack/train/feedfree.py", line 43, in run_step
    self.hooked_sess.run(self.train_op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 930, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/wrappers/framework.py", line 470, in run
    run_end_resp = self.on_run_end(run_end_req)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 267, in on_run_end
    self._dump_root, partition_graphs=partition_graphs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 524, in __init__
    self._load_partition_graphs(partition_graphs, validate)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 782, in _load_partition_graphs
    self._validate_dump_with_graphs()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 954, in _validate_dump_with_graphs
    (node, datum.timestamp, repr(pending_inputs[node])))
ValueError: Causality violated in timing relations of debug dumps: global_step/read (1490611843556445): these input(s) are not satisfied: [('global_step', 0)]
Prefetch process exited.
```
I have tried tfdebug with tensorpack in another example wriiten by myself. The same error occurs when training. But when I use OfflinePredictor to predict, tfdebug works fine.
The environment is: Ubuntu 16.04, tensorflow 1.1 installed from source. Use single TitanX GPU to train.

**Comment by ppwwyyxx** [comment]
It seems to be a limitation of tfdbg that it cannot work very well with queues.
Switching to SimpleTrainer might have tfdbg to work, since you won't care the speed anyway.
I'll do some more investigation later.

**Comment by ppwwyyxx** [comment]
Seems that a session.run call of a debug session cannot be run simultaneously in two threads. (which makes sense given what it did).
 But if using TF queues, then thread is necessary. It'll be hard to get around this limitation.

Apart from using SimpleTrainer, you can also just use the debug hook I mentioned [last time](https://github.com/ppwwyyxx/tensorpack/issues/191#issuecomment-287240204). It should be less error-prone than injecting a debug session and make every ops under inspection.

**Comment by JesseYang** [comment]
@ppwwyyxx Thanks! The debug hook works fine.
