### ISSUE TITLE
gradproc.py error

### ISSUE THREAD

**Issue by tangabc** [ppwwyyxx/tensorpack#232]
I tried to run the A3C-Gym example on an EC2 amazon p2.8xlarge instance (8 GPU + 32 vCPUs). However, I encountered the following error right from the beginning.

Please let me know if you have any insights as to why this error may occur.

```
[0418 02:14:10 @multigpu.py:38] Building graph for training tower 1...
[0418 02:14:10 @multigpu.py:38] Building graph for training tower 2...
[0418 02:14:11 @multigpu.py:38] Building graph for training tower 3...
Traceback (most recent call last):
  File "process-pnf.py", line 400, in <module>
    trainer(config).train()
  File "/home/ubuntu/a3c_test/tensorpack/train/base.py", line 61, in train
    self.setup()
  File "/home/ubuntu/a3c_test/tensorpack/train/base.py", line 118, in setup
    self._setup()   # subclass will setup the graph
  File "/home/ubuntu/a3c_test/tensorpack/train/multigpu.py", line 197, in _setup
    grad_list = apply_grad_processors(grad_list, [gradproc])
  File "/home/ubuntu/a3c_test/tensorpack/tfutils/gradproc.py", line 30, in apply_grad_processors
    g = proc.process(g)
  File "/home/ubuntu/a3c_test/tensorpack/tfutils/gradproc.py", line 50, in process
    return self._process(grads)
  File "/home/ubuntu/a3c_test/tensorpack/tfutils/gradproc.py", line 64, in _process
    for grad, var in grads:
ValueError: too many values to unpack
```

**Comment by ppwwyyxx** [comment]
Please use the latest version of tensorpack.

**Comment by tangabc** [comment]
I was using an older version of tensorpack (dated Feb '17). Let me try the latest version and see. Thanks.
