### ISSUE TITLE
A3C error when use GPU

### ISSUE THREAD

**Issue by ZhenghaoFei** [ppwwyyxx/tensorpack#233]
I tried use CPU and run A3C example code, everything works fun except cannot train.
When I switch to GPU,  error occurs.

[0418 11:07:05 @base.py:116] Setup callbacks graph ...
[0418 11:07:05 @base.py:187] Building predictor graph towerp0 on gpu=0 ...
Traceback (most recent call last):
  File "train-atari.py", line 291, in <module>
    trainer(config).train()
  File "/home/holly/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 93, in train
    self.setup()
  File "/home/holly/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 118, in setup
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/home/holly/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 44, in setup_graph
    self._setup_graph()
  File "/home/holly/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/group.py", line 77, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/home/holly/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 44, in setup_graph
    self._setup_graph()
  File "train-atari.py", line 161, in _setup_graph
    PREDICTOR_THREAD), batch_size=15)
  File "/home/holly/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/utils/develop.py", line 29, in __init__
    raise ImportError("Cannot import '{}', therefore '{}' is not available".format(dependency, klass))
ImportError: Cannot import 'tornado.concurrent', therefore 'MultiThreadAsyncPredictor' is not available
Segmentation fault (core dumped)

**Comment by ZhenghaoFei** [comment]
pip install tornado can solve the issue
