### ISSUE TITLE
Assertion error when running alexnet-dorefa

### ISSUE THREAD

**Issue by RyuLee** [ppwwyyxx/tensorpack#242]
I simply copied your "alexnet-dorefa.py" file and tried to run the pretrained model(downloaded from your google drive):
    ./alexnet-dorefa.py --load alexnet-126.npy --run a.jpg --dorefa 1,2,6
where I substitute "a.jpg" to my testing picture(224*224) and the running result looks like this:

[0426 18:10:27 @sessinit.py:187] WRN Variable lastbn/variance/EMA:0 in the dict not found in the graph!
[0426 18:10:27 @sessinit.py:190] Restoring from dict ...
Traceback (most recent call last):
  File "first_dorefa_alex.py", line 311, in <module>
    run_image(Model(), DictRestore(np.load(args.load, encoding='latin1').item()), args.run)
  File "first_dorefa_alex.py", line 261, in run_image
    predictor = OfflinePredictor(pred_config)
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\predict\base.py", line 147, in __init__
    config.session_init.init(sess)
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\tfutils\sessinit.py", line 30, in init
    self._init(sess)
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\tfutils\sessinit.py", line 34, in _init
    self._run_init(sess)
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\tfutils\sessinit.py", line 191, in _run_init
    upd.update({name: value for name, value in six.iteritems(self.prms) if name in intersect})
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\tfutils\varmanip.py", line 116, in update
    SessionUpdate.load_value_to_var(v, value)
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\tfutils\varmanip.py", line 77, in load_value_to_var
    "{}: {}!={}".format(name, varshape, val.shape)
AssertionError: fct/W: (4096, 1000)!=(512, 1000)

**Comment by ppwwyyxx** [comment]
You're not using the correct "alexnet-126.npy" file.

**Comment by RyuLee** [comment]
You got the point, I mistook the resnet file as alexnet file... but it came another bug below, it happend as well when I tried to train the model:

[0426 23:18:57 @sessinit.py:190] Restoring from dict ...
[0426 23:18:58 @fs.py:99] WRN $TENSORPACK_DATASET not set, using C:\Users\Pengyu Li/tensorpack_data for dataset.
caffe.proto: 65.5KB [00:01, 43.4KB/s]
Succesfully downloaded caffe.proto 58196 bytes.
caffe.proto: No such file or directory
Traceback (most recent call last):
  File "alexnet-dorefa.py", line 311, in <module>
    run_image(Model(), DictRestore(np.load(args.load, encoding='latin1').item()), args.run)
  File "alexnet-dorefa.py", line 262, in run_image
    meta = dataset.ILSVRCMeta()
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\dataflow\dataset\ilsvrc.py", line 33, in __init__
    self.caffepb = get_caffe_pb()
  File "D:\Software\Anaconda\envs\py35\lib\site-packages\tensorpack\utils\loadcaffe.py", line 128, in get_caffe_pb
    "Command `protoc caffe.proto --python_out .` failed!"
AssertionError: Command `protoc caffe.proto --python_out .` failed!

**Comment by ppwwyyxx** [comment]
You have to have protoc to run anything related to imagenet.
I don't know how to install it on windows.

**Comment by RyuLee** [comment]
Cheers! I figured it out, after manually moving some files from one to another. Appreciation. 👍 

BTW, if I want to use my own dataset, the path should look like:
    PATH/
      train/
        n02134418/
          n02134418_198.JPEG
          ...
        ...
      val/
        ILSVRC2012_val_00000001.JPEG
        ...
where is the label input to your model? If I have all pictures information contained in a file with format like:
    pic1.path label1
    pic2.path label2
    ....
any suggestions for adapting my dataset to your model?

**Comment by ppwwyyxx** [comment]
You need to write a DataFlow to handle your own data format. See [documentation](http://tensorpack.readthedocs.io/en/latest/tutorial/extend/dataflow.html)

**Comment by ppwwyyxx** [comment]
Feel free to reopen if you still have questions.
