### ISSUE TITLE
DoReFa Classification Error

### ISSUE THREAD

**Issue by laceyg** [ppwwyyxx/tensorpack#25]
When running the DoReFa alexnet-126.py classification example on a single image, I encounter the following error:

```
File "./alexnet-dorefa.py", line 304, in <module>
    run_image(Model(), ParamRestore(np.load(args.load).item()), args.run)
...
tensorflow.python.framework.errors.InvalidArgumentError: AttrValue must not have reference type value of float_ref
	 for attr 'dtype'
	; NodeDef: Placeholder = Placeholder[dtype=DT_FLOAT_REF, shape=[], _device="/device:CPU:0"](); Op<name=Placeholder; signature= -> output:dtype; attr=dtype:type; attr=shape:shape,default=[]>
```

I am running Python 2.7, and this issue occurs regardless of execution on CPU or GPU.  Any idea could be causing this?

**Comment by ppwwyyxx** [comment]
It still works for me. Are you using the latest tensorflow? If yes, could you paste more detailed error?

**Comment by laceyg** [comment]
Using tensorflow 0.9 with CUDA 7.5, Python 2.7, cuDNN 4.0.  Here is a more detailed error when I run on the CPU:

```
$ CUDA_VISIBLE_DEVICES=. ./alexnet-dorefa.py --load npy/alexnet-126.npy --run /tmp/ilsvrc12/test/ILSVRC2012_test_00100000.JPEG --dorefa 1,2,6
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.4.0.7 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
[0922 13:16:05 @format.py:25] WRN Error in 'import lmdb'. LMDBData won't be available.
[0922 13:16:06 @concurrency.py:27] WRN Cannot import Future in tornado.concurrent. MultiThreadAsyncPredictor won't be available.
[0922 13:16:06 @_common.py:61] conv0 input: [None, 224, 224, 3]
[0922 13:16:06 @_common.py:69] conv0 output: [None, 54, 54, 96]
[0922 13:16:06 @_common.py:61] conv1 input: [None, 54, 54, 96]
[0922 13:16:06 @alexnet-dorefa.py:88] Binarizing weight conv1/W
[0922 13:16:06 @_common.py:69] conv1 output: [None, 54, 54, 256]
[0922 13:16:06 @_common.py:61] pool1 input: [None, 54, 54, 256]
[0922 13:16:06 @_common.py:69] pool1 output: [None, 27, 27, 256]
[0922 13:16:06 @_common.py:61] conv2 input: [None, 27, 27, 256]
[0922 13:16:06 @alexnet-dorefa.py:88] Binarizing weight conv2/W
[0922 13:16:06 @_common.py:69] conv2 output: [None, 27, 27, 384]
[0922 13:16:06 @_common.py:61] pool2 input: [None, 27, 27, 384]
[0922 13:16:06 @_common.py:69] pool2 output: [None, 14, 14, 384]
[0922 13:16:06 @_common.py:61] conv3 input: [None, 14, 14, 384]
[0922 13:16:06 @alexnet-dorefa.py:88] Binarizing weight conv3/W
[0922 13:16:07 @_common.py:69] conv3 output: [None, 14, 14, 384]
[0922 13:16:07 @_common.py:61] conv4 input: [None, 14, 14, 384]
[0922 13:16:07 @alexnet-dorefa.py:88] Binarizing weight conv4/W
[0922 13:16:07 @_common.py:69] conv4 output: [None, 14, 14, 256]
[0922 13:16:07 @_common.py:61] pool4 input: [None, 14, 14, 256]
[0922 13:16:07 @_common.py:69] pool4 output: [None, 6, 6, 256]
[0922 13:16:07 @_common.py:61] fc0 input: [None, 6, 6, 256]
[0922 13:16:07 @alexnet-dorefa.py:88] Binarizing weight fc0/W
[0922 13:16:07 @_common.py:69] fc0 output: [None, 4096]
[0922 13:16:07 @_common.py:61] fc1 input: [None, 4096]
[0922 13:16:07 @alexnet-dorefa.py:88] Binarizing weight fc1/W
[0922 13:16:07 @_common.py:69] fc1 output: [None, 4096]
[0922 13:16:07 @_common.py:61] fct input: [None, 4096]
[0922 13:16:07 @_common.py:69] fct output: [None, 1000]
[0922 13:16:07 @regularize.py:17] Apply regularizer for fc0/W:0
[0922 13:16:07 @regularize.py:17] Apply regularizer for fc1/W:0
[0922 13:16:07 @regularize.py:17] Apply regularizer for fct/W:0
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: cop3
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: cop3
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.93  Tue Apr  5 18:18:24 PDT 2016

GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 352.93.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
[0922 13:16:07 @sessinit.py:154] Params to restore: bn3/gamma:0, bnfc0/variance/EMA:0, bn1/beta:0, fc0/W:0, conv2/W:0, bnfc1/gamma:0, conv4/W:0, bnfc0/gamma:0, bn3/beta:0, bn1/gamma:0, bn4/gamma:0, bn4/beta:0, bnfc0/mean/EMA:0, bn4/mean/EMA:0, bnfc0/beta:0, bn1/variance/EMA:0, fct/b:0, conv3/W:0, bn3/variance/EMA:0, bnfc1/variance/EMA:0, bnfc1/mean/EMA:0, bn2/gamma:0, bn1/mean/EMA:0, fct/W:0, conv0/W:0, bn3/mean/EMA:0, fc1/W:0, conv1/W:0, bn2/beta:0, bn4/variance/EMA:0, bn2/variance/EMA:0, bn2/mean/EMA:0, bnfc1/beta:0
[0922 13:16:07 @sessinit.py:164] Restoring from dict ...
Traceback (most recent call last):
  File "./alexnet-dorefa.py", line 304, in <module>
    run_image(Model(), ParamRestore(np.load(args.load).item()), args.run)
  File "./alexnet-dorefa.py", line 254, in run_image
    predict_func = get_predict_func(pred_config)
  File "/home/laceyg/tensorpack/tensorpack/predict/common.py", line 74, in get_predict_func
    return OfflinePredictor(config)
  File "/home/laceyg/tensorpack/tensorpack/predict/base.py", line 99, in __init__
    config.session_init.init(sess)
  File "/home/laceyg/tensorpack/tensorpack/tfutils/sessinit.py", line 31, in init
    self._init(sess)
  File "/home/laceyg/tensorpack/tensorpack/tfutils/sessinit.py", line 165, in _init
    upd.update({name: value for name, value in six.iteritems(self.prms) if name in intersect})
  File "/home/laceyg/tensorpack/tensorpack/tfutils/varmanip.py", line 71, in update
    self.sess.run(op, feed_dict={p: value})
  File "/home/laceyg/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/home/laceyg/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 640, in _run
    feed_dict_string, options, run_metadata)
  File "/home/laceyg/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/home/laceyg/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: AttrValue must not have reference type value of float_ref
	 for attr 'dtype'
	; NodeDef: Placeholder = Placeholder[dtype=DT_FLOAT_REF, shape=[], _device="/device:CPU:0"](); Op<name=Placeholder; signature= -> output:dtype; attr=dtype:type; attr=shape:shape,default=[]>
```

I may try to upgrade tensorflow to 0.10 to see if it resolves the issue.

**Comment by sujaynarumanchi** [comment]
Hi,
I faced the same issue with Tensorflow 0.9, but it worked when I upgraded to 0.10

**Comment by laceyg** [comment]
Upgrading to Tensforflow 0.10 fixed the problem for me as well - thanks for the advice!
