### ISSUE TITLE
How do I use tensorpack with nohup,because I want record the output.

### ISSUE THREAD

**Issue by dongzhuoyao** [ppwwyyxx/tensorpack#271]
[0515 23:44:28 @logger.py:84] WRN Directory train_log/cifar10-resnet exists! Please either backup/delete it, or use a new directory.
[0515 23:44:28 @logger.py:86] WRN If you're resuming from a previous run you can choose to keep it.
[0515 23:44:28 @logger.py:87] Select Action: k (keep) / b (backup) / d (delete) / n (new):
Traceback (most recent call last):
  File "cifar10-resnet.py", line 175, in <module>
    config = get_config()
  File "cifar10-resnet.py", line 144, in get_config
    logger.auto_set_dir()
  File "/home/guest2/.local/lib/python2.7/site-packages/tensorpack/utils/logger.py", line129, in auto_set_dir
    action=action)
  File "/home/guest2/.local/lib/python2.7/site-packages/tensorpack/utils/logger.py", line89, in set_logger_dir
    action = input().lower().strip()
IOError: [Errno 9] Bad file descriptor

**Comment by ppwwyyxx** [comment]
It will prompt you for action if the logging directory exists.
You can set a different directory #266 , or pass an action so it won't ask you for it, e.g. `auto_set_dir('d')`.
http://tensorpack.readthedocs.io/en/latest/modules/utils.html#tensorpack.utils.logger.set_logger_dir
