### ISSUE TITLE
ValueError(Variable conv0/W already exists) When Running cifar10-resnet.py

### ISSUE THREAD

**Issue by chengdazhi** [ppwwyyxx/tensorpack#277]
When I am running cifar10-resnet.py with no additional arguments, I get this ValueError: Variable conv0/W already exists, disallowed. I haven't made any modifications to the code.

The weights of the conv layer are not given explicitly, so I think it's a bug in tensorpack.

The exhaustive log information: (I have high-lighted logs that I find useful)

Traceback (most recent call last):
  File "cifar10-resnet.py", line 180, in <module>
    SyncMultiGPUTrainer(config).train()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 93, in train
    self.setup()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 118, in setup
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/base.py", line 44, in setup_graph
    self._setup_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/group.py", line 77, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/base.py", line 44, in setup_graph
    self._setup_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/inference_runner.py", line 115, in _setup_graph
    PredictorTowerBuilder(fn, self._prefix).build(self._predict_tower_id)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/predict/base.py", line 193, in build
    self._fn(tower)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/inference_runner.py", line 114, in fn
    self.trainer.model.build_graph(in_tensors)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/models/model_desc.py", line 105, in build_graph
    self._build_graph(model_inputs)
  **File "cifar10-resnet.py", line 78, in _build_graph
    l = Conv2D('conv0', image, 16, nl=BNReLU)**
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/models/common.py", line 131, in wrapped_func
    outputs = func(*args, **actual_args)
  **File "/usr/local/lib/python3.5/dist-packages/tensorpack/models/conv2d.py", line 60, in Conv2D**
    **W = tf.get_variable('W', filter_shape, initializer=W_init)**
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 639, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
**ValueError: Variable conv0/W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:**

  **File "/usr/local/lib/python3.5/dist-packages/tensorpack/models/conv2d.py", line 60, in Conv2D
    W = tf.get_variable('W', filter_shape, initializer=W_init)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/models/common.py", line 131, in wrapped_func**
    outputs = func(\*args, \*\*actual_args)
  **File "cifar10-resnet.py", line 78, in _build_graph
    l = Conv2D('conv0', image, 16, nl=BNReLU)**

**Comment by ppwwyyxx** [comment]
Cannot reproduced the problem. Could you tell how you installed tensorpack and tensorflow? Maybe one of them is outdated.

**Comment by chengdazhi** [comment]
Thanks for your prompt reply. I am using tensorflow 1.0.1 and the newest version of tensorpack. Should I upgrade tensorflow to 1.1.0 to fix this problem?

**Comment by ppwwyyxx** [comment]
I can reproduce the bug with 1.0.1. So probably a bug in TF.
