### ISSUE TITLE
Error when using dump-model-params

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#279]
I am using dump-model-params script to extract the weights from a ResNet34 run I had done a while back. I am getting this error:

```
Traceback (most recent call last):
  File "/home/Exps/extractWeights/tensorpack/scripts/dump-model-params.py", line 31, in <module>
    M = ModelFromMetaGraph(args.meta)
  File "/home/Exps/extractWeights/tensorpack/tensorpack/models/model_desc.py", line 173, in __init__
    "Collection {} not found in metagraph!".format(k)
AssertionError: Collection INPUTS_METAINFO not found in metagraph!
```

**Comment by ppwwyyxx** [comment]
Oh I probably renamed the collection some time ago.
This shouldn't affect dump-model-params. I'll fix it.
