### ISSUE TITLE
Is it possible to call eval() in callbacks function? 

### ISSUE THREAD

**Issue by deeplearningmachine** [ppwwyyxx/tensorpack#287]
This may be a silly question. 
With the following code, the system requires a datafeed. 

class OnlineExport(Callback):
    def _trigger_epoch(self):
        last_layer_rep=self.trainer.model.lastLayerRepresentation.eval()
...
callbacks=[
            ModelSaver(),
            OnlineExport(),
            InferenceRunner(dataset_test,[ScalarStats('cost'), ClassificationError()]),

**Comment by ppwwyyxx** [comment]
It should require a feed if your "lastLayerRepresentation" depends on a feed.

**Comment by deeplearningmachine** [comment]
Thanks. 
So how could I collect the real data from the lastLayerRepresentation of the ResNet? I need to collect several steps(epochs) of the lastLayerRepresentation  data and then run a clustering on the collection.

**Comment by ppwwyyxx** [comment]
What do you mean by real data?
Do you want to run the network in training mode or test mode?
Do you want to run it on the data you're currently trained on or some other data?
The easiest way if you just want to run the training network on the data you're currently trained, is to use `before_run` and `after_run`, which have identical API with `tf.train.SessionRunHook`.

And another problem is that why would your "lastLayerRepresentation" requires a feed. It shouldn't happen if inputs are properly defined by tensorpack. Could you post some logs on that?

**Comment by deeplearningmachine** [comment]
I meant the projected embeddings of the training data at the last layer (before the FC) of the ResNet. I need to collect all min-batches of one epoch before I can run my clustering.

It  was caused by the added eval() call in the middle of  of the main_loop(self) in the base.py. 
The complaint came from the InferenceRunner(dataset_test,[ScalarStats('cost'), ClassificationError()]) function. If I remove the InferenceRunner, everything works fine. Any example of using tf.train.SessionRunHook?

**Comment by ppwwyyxx** [comment]
I see what's going on. You're not supposed to use `model.lastLayerRepresentation` directly -- there are many of them. When you use multiGPU there is multiple of this tensors on each GPU. When you enable inference there is one extra of this tensor in the inference graph. Using `model.xxx` cannot give you the tensor you need.

For `before_run/after_run`:
```python
def _before_run(self, _):
    return ['fc/output']  # the name of the tensor(s) to eval. (you can also return a SessionRunArgs to be compatible with SessionRunHook). 

def _after_run(self, _, values):
    # values.results contain the value of the tensors
```
See https://www.tensorflow.org/api_docs/python/tf/train/SessionRunHook.

**Comment by deeplearningmachine** [comment]
Finalize the graph, create the session ...
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:0a:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0)
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:2 for node 'tower2/input_deque' because the input edge from 'input_queue' is a reference connection and already has a device field set to /GPU:3
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:1 for node 'tower1/input_deque' because the input edge from 'input_queue' is a reference connection and already has a device field set to /GPU:3
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:0 for node 'tower0/input_deque' because the input edge from 'input_queue' is a reference connection and already has a device field set to /GPU:3
[0602 13:49:13 @base.py:132] Graph variables initialized.
[0602 13:49:13 @concurrency.py:36] Starting EnqueueThread ...
[0602 13:49:13 @base.py:167] Start Epoch 1 ...
  0%|                                                                                                              |0/390[00:00<?,?it/s]
W tensorflow/core/kernels/queue_base.cc:294] _0_input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
[0602 13:49:16 @input_data.py:125] EnqueueThread Exited.
  File "nips-cifar10-resnet.py", line 599, in <module>
    SyncMultiGPUTrainer(config).train()
  File "/data/datapk/tensorpack/tensorpack/train/base.py", line 96, in train
    self.main_loop()
  File "/data/datapk/tensorpack/tensorpack/train/base.py", line 240, in main_loop
    last_layer_rep.append(self.model.lastLayerRepresentation.eval())
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 567, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3729, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input' with dtype float
         [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: towerp0/gap/output/_3953 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_683_towerp0/gap/output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'input', defined at:
  File "nips-cifar10-resnet.py", line 599, in <module>
    SyncMultiGPUTrainer(config).train()
  File "/data/datapk/tensorpack/tensorpack/train/base.py", line 95, in train
    self.setup()
  File "/data/datapk/tensorpack/tensorpack/train/base.py", line 110, in setup
    self._setup()   # subclass will setup the graph
  File "/data/datapk/tensorpack/tensorpack/train/multigpu.py", line 112, in _setup
    super(SyncMultiGPUTrainer, self)._setup()
  File "/data/datapk/tensorpack/tensorpack/train/feedfree.py", line 39, in _setup
    self._input_method.setup_training(self)
  File "/data/datapk/tensorpack/tensorpack/train/input_data.py", line 158, in setup_training
    super(QueueInput, self).setup_training(trainer)
  File "/data/datapk/tensorpack/tensorpack/train/input_data.py", line 39, in setup_training
    self.setup(trainer.model)
  File "/data/datapk/tensorpack/tensorpack/train/input_data.py", line 148, in setup
    self.input_placehdrs = model.get_reused_placehdrs()
  File "/data/datapk/.local/lib/python2.7/site-packages/functools32/functools32.py", line 378, in wrapper
    result = user_function(*args, **kwds)
  File "/data/datapk/tensorpack/tensorpack/models/model_desc.py", line 64, in get_reused_placehdrs
    return self.build_placeholders()
  File "/data/datapk/tensorpack/tensorpack/models/model_desc.py", line 88, in build_placeholders
    name=prefix + v.name))
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1502, in placeholder
    name=name)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2149, in _placeholder
    name=name)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/data/datapk/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input' with dtype float
         [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: towerp0/gap/output/_3953 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_683_towerp0/gap/output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by ppwwyyxx** [comment]
You can also checkout an existing summary callback using `before_run/after_run`: https://github.com/ppwwyyxx/tensorpack/blob/7775587529118f2c3dcb28fd9bc30a2b259e57c9/tensorpack/callbacks/summary.py#L54

**Comment by deeplearningmachine** [comment]
Thanks a lot for the help!

**Comment by deeplearningmachine** [comment]
Would the tensors in different towers return the same results for the _after_run? 
Thanks!

**Comment by ppwwyyxx** [comment]
No because different GPUs train on different data.
If you need them all just add them in before_run.

**Comment by deeplearningmachine** [comment]
many thanks!

**Comment by deeplearningmachine** [comment]
before_run is just able to collect the current mini-batch data or can collect all the mini batches in a epoch? In order to have the projected representations of all the training data, I will need to collect the last layer's representations of all batches of an epoch in all the GPU towers, is it correct?

**Comment by ppwwyyxx** [comment]
before_run/after_run is called together with every `sess.run`. That is every step in an epoch.

**Comment by deeplearningmachine** [comment]
yeah, a tutorial with some examples about callbacks will be greatly beneficial for sure!
