### ISSUE TITLE
ResNet ModelZoo

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#298]
Are there any pretrained ResNet models? I get
```
patwie@pc~/git/tensorpack/examples/ResNet (master) $ ./load-resnet.py --load /tensorpack_data/ImageNet-ResNet50.npy --input cat.jpg --depth 50
[0614 16:42:56 @load-resnet.py:218] ERR Exception when processing caffe layer group2/block4/preact/bn/variance/EMA:0
Traceback (most recent call last):
  File "./load-resnet.py", line 216, in <module>
    newname = name_conversion(k)
  File "./load-resnet.py", line 172, in name_conversion
    layer_block_part1 = s.group(3)
AttributeError: 'NoneType' object has no attribute 'group'
```

when using the model from 
https://drive.google.com/drive/folders/0B9IPQTvr2BBkTXBlZmh1cmlnQ0k

**Comment by ppwwyyxx** [comment]
#58
