### ISSUE TITLE
SyncMultiGPUTrainer and ProgressBar

### ISSUE THREAD

**Issue by kdplus** [ppwwyyxx/tensorpack#315]
I get an error when I use the SyncMultiGPUTrainer.
But in SimpleTrainer(config).train() the progressBar works fine
:
```
[0627 15:39:01 @concurrency.py:36] Starting EnqueueThread ...                                                             [40/1912]
Traceback (most recent call last):
  File "model_pack.py", line 187, in <module>
    # SyncMultiGPUTrainer(config).train()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/train/base.py", line 104, in train
    self.main_loop()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/train/base.py", line 178, in main_loop
    self._callbacks.before_train()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 59, in before_train
    self._before_train()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 68, in _before_train
    cb.before_train()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 59, in before_train
    self._before_train()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/callbacks/steps.py", line 104, in _before_train
    self._fetches = get_op_or_tensor_by_name(self._names) or None
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/tfutils/common.py", line 142, in get_op_or_tenso
r_by_name
    return list(map(f, name))
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/tfutils/common.py", line 135, in f
    return G.get_tensor_by_name(n)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2563, in get_tens
or_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2411, in as_graph
_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2456, in _as_grap
h_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'cost:0' refers to a Tensor which does not exist. The operation, 'cost', does not exist in the graph."
```

Here is my config code:
```
def get_config():
    logger.auto_set_dir()
    with open('../config.json') as cfg:
        config = json.load(cfg)
    dataset_train, dataset_test = run(config)
    extra_display = ["cost", "accuracy", "train_error"]

    return TrainConfig(
        dataflow=dataset_train.ds,
        callbacks=[
            ModelSaver(keep_checkpoint_every_n_hours=0.2),
            # InferenceRunner(dataset_test.ds,
            #                 [ScalarStats('cost'), 
            #                 ClassificationError('wrong-top1', 'val-error-top1')]),
            ScheduledHyperParamSetter('learning_rate',
                                    [(1, 0.1), (82, 0.01), (123, 0.001), (300, 0.0002)])
        ],
        extra_callbacks=[  
            MovingAverageSummary(),
            ProgressBar(extra_display),
            MergeAllSummaries(),
            RunUpdateOps(),
        ],
        monitors=[    
            tensorpack.callbacks.TFEventWriter(),
            tensorpack.callbacks.JSONWriter(),
            tensorpack.callbacks.ScalarPrinter(enable_step=True),
        ],
        model=Model(1),
        max_epoch=4,
    )
```

**Comment by PatWie** [comment]
In the multi-Tower setting you need to use 
```python
ProgressBar(['tower0/cost']),
```

Each tower has its own scope. To get the name of the Tensor, I do something like

```python
self.cost = bla bla bla
print(self.cost.name)
```

This should give the name for the progressbar.

@ppwwyyxx Should I add some logic to look into Tower 0, if no tensor was found?

**Comment by ppwwyyxx** [comment]
@kdplus Please try the above suggestion.
@PatWie This is a big problem with the current interface, also brought out by some others earlier. I would want to improve clarity of ModelDesc in different aspects, but haven't got a concrete plan yet.

**Comment by kdplus** [comment]
@PatWie @ppwwyyxx Thx! It works

**Comment by PatWie** [comment]
@ppwwyyxx I still do not get it, why it should be a problem. After all it is an entire computation graph. And the issues comes with Tf itself.
TensorPack can provide a function `get_tensor` which tries to be smart enough to test whether there is a training tower or not.

**Comment by ppwwyyxx** [comment]
About the original question, after latest changes 897d29e to the trainer, using "cost" would be sufficient. "tower0/cost" also works.
