### ISSUE TITLE
Predictor load checkpoint failed

### ISSUE THREAD

**Issue by kdplus** [ppwwyyxx/tensorpack#325]
I saved a model checkpoint using Trainconfig callback
```
    return TrainConfig(
        dataflow=dataset_train.ds,
        callbacks=[
            KerasCallback(1), 
            PeriodicTrigger(ModelSaver(max_to_keep=100), every_k_steps=200),
```
And it works well during training(I can stop the training and restore from the checkpoint)
I use `SyncMultiGPUTrainer(config).train()` so its variable name have the "tower*" prefix,
Then I want to restore the model when predicting, thus I use the `predictConfig` as the following code, but it seems cannot found the variable correctly due to the variable name
```
pred = PredictConfig(
        model=md(1),
        session_init=get_model_loader(load),
        input_names=['input'],
        output_names=['output']
    )

 pred = OfflinePredictor(pred)
```
```
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_2/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_2/gamma in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_2/beta in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_2/moving_mean in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_2/moving_variance in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_3/kernel in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_3/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_3/gamma in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_3/beta in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_3/moving_mean in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_3/moving_variance in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_4/kernel in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_4/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_4/gamma in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_4/beta in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_4/moving_mean in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_4/moving_variance in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_5/kernel in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_5/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_5/gamma in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_5/beta in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_5/moving_mean in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_5/moving_variance in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_6/kernel in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_6/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_6/gamma in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_6/beta in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_6/moving_mean in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_6/moving_variance in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_7/kernel in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable conv3d_7/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_7/gamma in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_7/beta in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_7/moving_mean in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable batch_normalization_7/moving_variance in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable dense_1/kernel in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable dense_1/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable dense_2/kernel in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:128] WRN Variable dense_2/bias in the graph not found in checkpoint!
[0706 13:14:30 @sessinit.py:133] WRN Variable beta1_power:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable beta2_power:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable global_step:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable input_queue_size/EMA:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable learning_rate:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/accuracy/EMA:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_1/beta:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_1/gamma:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_1/moving_mean:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_1/moving_variance:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_2/beta:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_2/gamma:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_2/moving_mean:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_2/moving_variance:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_3/beta:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_3/gamma:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_3/moving_mean:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_3/moving_variance:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_4/beta:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_4/gamma:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_4/moving_mean:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_4/moving_variance:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_5/beta:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_5/gamma:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_5/moving_mean:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_5/moving_variance:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_6/beta:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_6/gamma:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_6/moving_mean:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_6/moving_variance:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_7/beta:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_7/gamma:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_7/moving_mean:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/batch_normalization_7/moving_variance:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_1/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_1/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_2/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_2/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_3/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_3/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_4/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_4/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_5/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_5/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_6/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_6/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_7/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/conv3d_7/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/cost/EMA:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/cross_entropy_loss/EMA:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/dense_1/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/dense_1/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/dense_2/bias:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/dense_2/kernel:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/train-error-top1/EMA:0 in checkpoint not found in the graph!
[0706 13:14:30 @sessinit.py:133] WRN Variable tower0/train_error/EMA:0 in checkpoint not found in the graph!
Traceback (most recent call last):
  File "src/evaluate.py", line 463, in <module>
    main()
  File "src/evaluate.py", line 456, in main
    scores = evaluate(nodules, arguments['<data_path>'], arguments['<model>'], n_gpus=n_gpus, load=arguments['<load>'])
  File "src/evaluate.py", line 374, in evaluate
    pred = OfflinePredictor(pred)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/predict/base.py", line 145, in __init__
    config.session_init.init(sess)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 30, in init
    self._init(sess)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 33, in _init
    self._setup_graph()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 99, in _setup_graph
    self.saver = tf.train.Saver(var_list=dic, name=str(id(dic)))
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1077, in build
    raise ValueError("No variables to save")

```

What's the correct way to use the predictor to restore a model over multi-gpu ?

**Comment by ppwwyyxx** [comment]
Things would work just fine if you don't use Keras model. I believe that's because Keras use `tf.Variable` to create variables instead of `tf.get_variable`.

If you really want to use Keras model, either add a `tf.name_scope('tower0')` at predict time, or modify your checkpoint to remove the `tower0` prefix.

**Comment by kdplus** [comment]
@ppwwyyxx Thx, I tried append a `savename_prefix=tower0` in `get_savename_from_varname`. It works for me. 
I'd like to try to add a `tf.name_scope('tower0')` It should work well.

And another question is that the model is restored but due to the Keras model callback
```
class KerasCallback(Callback):
    def __init__(self, isTrain):
        self._isTrain = isTrain
        self._learning_phase = KB.learning_phase()

    def _before_run(self, ctx):
        return tf.train.SessionRunArgs(
            fetches=[], feed_dict={self._learning_phase: int(self._isTrain)})
```
it give me an error when I try to  `pred = OfflinePredictor(pred)`
```
[0706 20:08:47 @sessinit.py:102] Restoring checkpoint from /mnt/ficusspain/yxwang/research_lung/08_all_e2e2/506_resume-95/cls_3d/src/train_log/model_kp:./train_keras/model-74478 ...
Traceback (most recent call last):
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: output/_101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_239_output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/evaluate.py", line 470, in <module>
    main()
  File "src/evaluate.py", line 463, in main
    scores = evaluate(nodules, arguments['<data_path>'], arguments['<model>'], n_gpus=n_gpus, load=arguments['<load>'])
  File "src/evaluate.py", line 386, in evaluate
    result = pred([batch])[0]
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/predict/base.py", line 55, in __call__
    output = self._do_call(dp)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/predict/base.py", line 122, in _do_call
    output = self.sess.run(self.output_tensors, feed_dict=feed)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: output/_101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_239_output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'batch_normalization_1/keras_learning_phase', defined at:
  File "src/evaluate.py", line 470, in <module>
    main()
  File "src/evaluate.py", line 463, in main
    scores = evaluate(nodules, arguments['<data_path>'], arguments['<model>'], n_gpus=n_gpus, load=arguments['<load>'])
  File "src/evaluate.py", line 384, in evaluate
    pred = OfflinePredictor(pred)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/predict/base.py", line 139, in __init__
    config.model.build_graph(input_placehdrs)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/models/model_desc.py", line 105, in build_graph
    self._build_graph(model_inputs)
  File "/mnt/ficusspain/yxwang/research_lung/08_all_e2e2/000_nodule_workspace_template/cls_3d/src/model_kp.py", line 238, in _build_graph
    M = self._build_keras_model()
  File "/mnt/ficusspain/yxwang/research_lung/08_all_e2e2/000_nodule_workspace_template/cls_3d/src/model_kp.py", line 74, in _build_keras_model
    model.add(normalization.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True, beta_initializer='zeros', gamma_initializer='ones', moving_mean_initializer='zeros', moving_variance_initializer='ones', beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/keras/models.py", line 476, in add
    output_tensor = layer(self.outputs[0])
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/keras/layers/normalization.py", line 190, in call
    training=training)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2600, in in_train_phase
    training = learning_phase()
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 116, in learning_phase
    name='keras_learning_phase')
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1507, in placeholder
    name=name)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1997, in _placeholder
    name=name)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: output/_101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_239_output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: output/_101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_239_output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```
Is there any good way to handle this placeholder problem, I am not very familiar with tensorflow. 
Thx!

**Comment by kdplus** [comment]
https://github.com/fchollet/keras/issues/2310  I found this but it doesn't work for me

**Comment by kdplus** [comment]
I now know the right way to use the restored model 
`result = pred([batch, 0])[0]` 
you need add one more parameter after input data for learning_phase flag

**Comment by ppwwyyxx** [comment]
You can add `keras.backend.learning_phase().name` to `input_names` in `PredictConfig`, and call it with an extra zero: `result = pred([batch, 0])[0]`

**Comment by kdplus** [comment]
`keras.backend.learning_phase()` seems to be an int, hence does not have a `name`. Is there a variable or    tensor things to get a correct name?

**Comment by ppwwyyxx** [comment]
You might be using old version of Keras.
```
$ keras.backend.learning_phase()
Out[4]: <tf.Tensor 'keras_learning_phase:0' shape=<unknown> dtype=bool>
```

**Comment by kdplus** [comment]
I called **K.set_learning_phase(1)** this before keras.backend.learning_phase().name. Now I comment this line, and get the correct name ''keras_learning_phase"
But it seems does not exist in the graph
Traceback (most recent call last):
  File "src/evaluate.py", line 486, in <module>
    main()
  File "src/evaluate.py", line 479, in main
    scores = evaluate(nodules, arguments['<data_path>'], arguments['<model>'], n_gpus=n_gpus, load=arguments['<load>'])
  File "src/evaluate.py", line 397, in evaluate
    pred = OfflinePredictor(pred)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/predict/base.py", line 141, in __init__
    input_tensors = get_tensors_by_names(config.input_names)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorpack/tfutils/common.py", line 120, in get_tensors_by_names
    ret.append(G.get_tensor_by_name(varn))
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2563, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2414, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/yxwang/.pyenv/versions/threed/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2456, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'keras_learning_phase:0' refers to a Tensor which does not exist. The operation, 'keras_learning_phase', does not exist in the graph."

**Comment by kdplus** [comment]
In my case the learning_phase's name actually is
`batch_normalization_1/keras_learning_phase`
which is different with `keras.backend.learning_phase()`
hence after I add this name to `input_names` of `PredictConfig`
and use `result = pred([batch, 0])[0]` when predicting
It works well now!

**Comment by ppwwyyxx** [comment]
You need to actually call `learning_phase().name` to get the name, instead of just adding the name to input_names.

**Comment by ppwwyyxx** [comment]
Just looked at keras code a bit, looks like there is no way to know what the actual name of `learning_phase` will be before the graph is created.

**Comment by kdplus** [comment]
A strange thing happens to me, the `OfflinePredictor` always produce the same inference results for every batch and even same result for every single data in the batch. 
I checked the batch data are different and my model value is correct. Do you have any idea for this kind of error? thx
By the way, there still some name scope related problems when I try to use the `DataParallelOfflinePredictor`.

**Comment by ppwwyyxx** [comment]
I don't know what happened in your model.
And I don't know what name scope problems you saw.

**Comment by kdplus** [comment]
thx, I also tried to use the basic tensorflow layer (because I need use conv3d) but it's training accuracy was stuck at 50%  for a binary classification problem...
but, after I used the keras to build the model everything works fine.(but followed by lots of other issues

**Comment by ppwwyyxx** [comment]
If you still have any specific questions feel free to reopen the issue.
