### ISSUE TITLE
AssertionError running GAN samples

### ISSUE THREAD

**Issue by Kukanani** [ppwwyyxx/tensorpack#361]
Hello,

I'm just beginning with TensorPack, and I was able to install it and run training on the ConditionalGAN-mnist example. Now, when trying to generate samples, I get the following output:
```
$ ./ConditionalGAN-mnist.py --load train_log/ConditionalGAN-mnist/model-2000.data-00000-of-00001 --sample
Failed to load OpenCL runtime (expected version 1.1+)
[0803 15:48:21 @varmanip.py:163] WRN Checkpoint path train_log/ConditionalGAN-mnist/model-2000.data-00000-of-00001 is auto-corrected to train_log/ConditionalGAN-mnist/model-2000.
Traceback (most recent call last):
  File "./ConditionalGAN-mnist.py", line 144, in <module>
    sample(args.load)
  File "./ConditionalGAN-mnist.py", line 123, in sample
    output_names=['gen/gen'])
  File "/home/adam/.virtualenvs/cv/local/lib/python2.7/site-packages/tensorpack/predict/config.py", line 43, in __init__
    assert_type(self.model, ModelDesc)
  File "/home/adam/.virtualenvs/cv/local/lib/python2.7/site-packages/tensorpack/predict/config.py", line 41, in assert_type
    assert isinstance(v, tp), v.__class__
AssertionError: <class '__main__.Model'>
```
Unfortunately I'm not a strong Python developer, so I'm having trouble debugging this on my own. I also wonder if this has anything to do with my use of Python2.

**Comment by ppwwyyxx** [comment]
It is a bug.

**Comment by ppwwyyxx** [comment]
Thanks for reporting !
