### ISSUE TITLE
example codes crashed (ResNet)

### ISSUE THREAD

**Issue by chunfuchen** [ppwwyyxx/tensorpack#368]
After I updated the newest changes, the training for ResNet 50 is crashed; however, the inference is fine. (I clean install the newest version to avoid my changes in source codes.)
Thanks!

my command:

```
python3 examples/ResNet/imagenet-resnet.py --gpu 0,1,2,3 --data /home/chenrich/dataset/imagenet -d 50
```

Here is log:
```
[0808 10:09:00 @input_source.py:427] Pre-filling staging area ...
[0808 10:09:00 @input_source.py:195] ERR Exception in EnqueueThread:
Traceback (most recent call last):
  File "~/Developer/temp/tensorpack/tensorpack/graph_builder/input_source.py", line 186, in run
    self.dataflow.reset_state()
  File "~/Developer/temp/tensorpack/tensorpack/dataflow/base.py", line 79, in reset_state
    self.ds.reset_state()
  File "~/Developer/temp/tensorpack/tensorpack/dataflow/prefetch.py", line 183, in reset_state
    self.start_processes()
  File "~/Developer/temp/tensorpack/tensorpack/dataflow/prefetch.py", line 189, in start_processes
    start_proc_mask_signal(self.procs)
  File "~/Developer/temp/tensorpack/tensorpack/utils/concurrency.py", line 188, in start_proc_mask_signal
    with mask_sigint():
  File "~/tools/Python-3.6.2/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "~/Developer/temp/tensorpack/tensorpack/utils/concurrency.py", line 174, in mask_sigint
    sigint_handler = signal.signal(signal.SIGINT, signal.SIG_IGN)
  File "~/tools/Python-3.6.2/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
[0808 10:09:00 @input_source.py:201] EnqueueThread Exited.
```

**Comment by ppwwyyxx** [comment]
My bad.
