### ISSUE TITLE
Run cifar-10 residual net?

### ISSUE THREAD

**Issue by yihui-he** [ppwwyyxx/tensorpack#4]
> [25 17:32:54 28@cifar10.py:tensorpack] Found cifar10 data in /home/eli/Downloads/tensorpack-master/tensorpack/dataflow/dataset/cifar10_data.
[25 17:32:55 28@cifar10.py:tensorpack] Found cifar10 data in /home/eli/Downloads/tensorpack-master/tensorpack/dataflow/dataset/cifar10_data.
Traceback (most recent call last):
  File "cifar10-resnet.py", line 196, in <module>
    QueueInputTrainer(config).train()
  File "/home/eli/Downloads/tensorpack-master/tensorpack/train/trainer.py", line 185, in train
    grads = self._single_tower_grad()
  File "/home/eli/Downloads/tensorpack-master/tensorpack/train/trainer.py", line 134, in _single_tower_grad
    cost_var = self.model.get_cost(model_inputs, is_training=True)
  File "/home/eli/Downloads/tensorpack-master/tensorpack/models/model_desc.py", line 53, in get_cost
    return self._get_cost(input_vars, is_training)
  File "cifar10-resnet.py", line 83, in _get_cost
    l = conv('conv0', image, 16, 1)
  File "cifar10-resnet.py", line 52, in conv
    W_init=tf.random_normal_initializer(stddev=np.sqrt(2.0/9/channel)))
  File "<decorator-gen-4>", line 2, in Conv2D
TypeError: wrapper() takes exactly 1 argument (11 given)
[25 17:32:56 59@prefetch.py:tensorpack] Prefetch process exiting...
[25 17:32:56 63@prefetch.py:tensorpack] Prefetch process exited.

**Comment by ppwwyyxx** [comment]
Sorry I introduced a bug yesterday. I'll work on a fix soon. For the moment you can checkout to fd21c3b1afa4b870bbd5f12c1f68e264aafe4c02 or before.

Also please use the command line argument to specify the gpu. e.g.:
```
./cifar10-resnet.py --gpu 0
```

**Comment by ppwwyyxx** [comment]
Fixed in 13f76d5c3774d99e62

**Comment by yihui-he** [comment]
Many thanks.
