### ISSUE TITLE
Running Cycle GAN error after epoch3

### ISSUE THREAD

**Issue by AkhilSinghRana** [ppwwyyxx/tensorpack#411]
Hi After epoch 3, There is a call to this fuunction 
 callbacks=[
            ModelSaver(),
            ScheduledHyperParamSetter(
                'learning_rate',
                [(100, 2e-4), (200, 0)], interp='linear'),
            PeriodicTrigger(**VisualizeTestSet(), every_k_epochs=3**), #Value changed from 3 just for training 
        ],vvvv
which throws error. I am not sure why this error comes, But I am guessing it is because of dataflow function in preprocess.py called  "PrefetchDataZMQ" Object has no attribute socket. I am not sure what this really means. I am attaching the error below.

 W tensorflow/core/kernels/queue_base.cc:295] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "tensorpack/examples/GAN/CycleGAN.py", line 234, in <module>
    GANTrainer(config).train()
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/train/base.py", line 136, in train
    self.main_loop()
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/train/base.py", line 241, in main_loop
    self._callbacks.trigger_epoch()
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 151, in trigger_epoch
    self._trigger_epoch()
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/callbacks/group.py", line 91, in _trigger_epoch
    cb.trigger_epoch()
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 151, in trigger_epoch
    self._trigger_epoch()
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/callbacks/trigger.py", line 43, in _trigger_epoch
    self.cb.trigger()
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 160, in trigger
    self._trigger()
  File "tensorpack/examples/GAN/CycleGAN.py", line 200, in _trigger
    for iA, iB in self.val_ds.get_data():
  File "/home/NOVA/akhil.singh-rana/MyWorkspace/MyProjects/tensorpack/env/lib/python2.7/site-packages/tensorpack/dataflow/prefetch.py", line 171, in get_data
    dp = loads(self.socket.recv(copy=False).bytes)
AttributeError: 'PrefetchDataZMQ' object has no attribute 'socket'[0906 17:50:24 @input_source.py:203] EnqueueThread QueueInput/input_queue Exited.

I have changed the visualiyation to after epoch 193, Hope that helps me atleast train the model ?

**Comment by AkhilSinghRana** [comment]
Hi could you resolve visualization on test set after every 3 epochs.  

Thanks,
Akhil

**Comment by ppwwyyxx** [comment]
It should be fixed 14 days ago.

**Comment by AkhilSinghRana** [comment]
Hi thanks I will try again. 
Cheers
