### ISSUE TITLE
installing tensorpack to a local folder results in import error with realtive paths

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#419]
this is on linux with python 3.6.2 and tf 1.3
i install tensorpack into a folder named 'site-packages' inside my project. i then add it to the path with a relative reference.

pip install -U git+git://github.com/ppwwyyxx/tensorpack.git -t site-packages
python
>>> import sys
>>> sys.path.insert(1,"site-packages")
>>> import tensorflow #this works
>>> import tensorpack #this fails for a relative path but works for an absolute path

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages/tensorpack/__init__.py", line 13, in <module>
    from tensorpack.models import *
  File "site-packages/tensorpack/models/__init__.py", line 31, in <module>
    _global_import(module_name)
  File "site-packages/tensorpack/models/__init__.py", line 15, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "site-packages/tensorpack/models/batch_norm.py", line 7, in <module>
    from tensorflow.contrib.framework import add_model_variable
  File "site-packages/tensorflow/contrib/__init__.py", line 22, in <module>
    from tensorflow.contrib import bayesflow
  File "site-packages/tensorflow/contrib/bayesflow/__init__.py", line 24, in <module>
    from tensorflow.contrib.bayesflow.python.ops import csiszar_divergence
  File "site-packages/tensorflow/contrib/bayesflow/python/ops/csiszar_divergence.py", line 26, in <module>
    from tensorflow.contrib.bayesflow.python.ops.csiszar_divergence_impl import *
  File "site-packages/tensorflow/contrib/bayesflow/python/ops/csiszar_divergence_impl.py", line 42, in <module>
    from tensorflow.contrib import framework as contrib_framework
  File "site-packages/tensorflow/contrib/framework/__init__.py", line 89, in <module>
    from tensorflow.contrib.framework.python.ops import *
  File "site-packages/tensorflow/contrib/framework/python/ops/__init__.py", line 24, in <module>
    from tensorflow.contrib.framework.python.ops.checkpoint_ops import *
  File "site-packages/tensorflow/contrib/framework/python/ops/checkpoint_ops.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_checkpoint_ops.so"))
  File "site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: site-packages/tensorflow/contrib/util/site-packages/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so: cannot open shared object file: No such file or directory

**Comment by ppwwyyxx** [comment]
From the logs it looks like it will fail if you `import tensorflow.contrib`. I don't think it's related to tensorpack.

**Comment by eyaler** [comment]
https://github.com/tensorflow/tensorflow/issues/13126
