### ISSUE TITLE
Usage Question about AccumGradOptimizer

### ISSUE THREAD

**Issue by xiaosongwang** [ppwwyyxx/tensorpack#435]
Hi ppwwyyxx,

I have a usage question when I try to use
...
        opt = tf.train.AdamOptimizer(lr)
        opt = AccumGradOptimizer(opt, 5)
...
Error message I got:

AssertionError: AccumGradOptimizer only works for dense update! Types of v and g are <class 'tensorflow.python.ops.variables.Variable'> and <class 'tensorflow.python.framework.ops.IndexedSlices'>

Could you give some hint why is this happening? Many thanks!

Best,
Xiaosong

**Comment by ppwwyyxx** [comment]
You might be using some operations in the model e.g. slicing of variables, that this implementation of accumgrad doesn't support yet.

**Comment by xiaosongwang** [comment]
OK, thanks

**Comment by hbellafkir** [comment]
I hava a model that uses slicing operations, did you fix the problem ?

**Comment by ppwwyyxx** [comment]
It's now supported since 40c3ab6a68b56507c584b80522e7c86884255f13

**Comment by hbellafkir** [comment]
im using keras ResNet50 in a tensorflow training loop as:
```
self.sess = tf.Session(config=config_proto)
tf.keras.backend.set_session(self.sess)
self.img = tf.placeholder(tf.float32, [None, 256, 256, 3])
self.model = tf.keras.applications.ResNet50(input_tensor=self.img,
                                                include_top=False,
                                                weights=None,
                                                pooling='avg')
dense = tf.keras.layers.Dense(64)
out = dense(init_model.layers[-1].output)
.
.
.
self.sess.run(tf.global_variables_initializer())
self.model.load_weights(self.model_weights)
opt = tf.train.MomentumOptimizer(learning_rate=self.lr, momentum=0.9)
opt = AccumGradOptimizer(opt,self.iter_size)
.
.
.

```

and I got this error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access resource conv1/kernel located in device /job:localhost/replica:0/task:0/device:GPU:0 from device /job:localhost/replica:0/task:0/device:CPU:0
	 [[Node: AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum = ResourceApplyMomentum[T=DT_FLOAT, use_locking=false, use_nesterov=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](AccumGradOptimizer/cond/Momentum/update_conv1/kernel/Read/ReadVariableOp/Switch/_4783, AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum/Switch:1, AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum/Switch_1/_4785, AccumGradOptimizer/cond/ReadVariableOp, AccumGradOptimizer/cond/Momentum/momentum/_4787)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_val_script.py", line 75, in <module>
    model_weights = model.train(train_img, database_img, query_img, args)
  File "/DeepHash/DeepHash/model/dtq/__init__.py", line 10, in train
    model.train_cq(img_train, img_query, img_database, config.R)
  File "/DeepHash/DeepHash/model/dtq/dtq.py", line 382, in train_cq
    self.b_img: codes})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access resource conv1/kernel located in device /job:localhost/replica:0/task:0/device:GPU:0 from device /job:localhost/replica:0/task:0/device:CPU:0
	 [[Node: AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum = ResourceApplyMomentum[T=DT_FLOAT, use_locking=false, use_nesterov=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](AccumGradOptimizer/cond/Momentum/update_conv1/kernel/Read/ReadVariableOp/Switch/_4783, AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum/Switch:1, AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum/Switch_1/_4785, AccumGradOptimizer/cond/ReadVariableOp, AccumGradOptimizer/cond/Momentum/momentum/_4787)]]

Caused by op 'AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum', defined at:
  File "train_val_script.py", line 75, in <module>
    model_weights = model.train(train_img, database_img, query_img, args)
  File "/DeepHash/DeepHash/model/dtq/__init__.py", line 6, in train
    model = DTQ(config)
  File "/DeepHash/DeepHash/model/dtq/dtq.py", line 112, in __init__
    self.train_op = self.apply_loss_function(self.global_step)
  File "/DeepHash/DeepHash/model/dtq/dtq.py", line 244, in apply_loss_function
    return opt.apply_gradients(grads_and_vars, global_step=global_step)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/optimizer.py", line 219, in apply_gradients
    op = tf.cond(pred, update_grad, tf.no_op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2048, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1895, in BuildCondBranch
    original_result = fn()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/optimizer.py", line 210, in update_grad
    update_op = self._opt.apply_gradients(slots_and_vars)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 605, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 166, in update_op
    update_op = optimizer._resource_apply_dense(g, self._v)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/momentum.py", line 108, in _resource_apply_dense
    use_nesterov=self._use_nesterov)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gen_training_ops.py", line 1750, in resource_apply_momentum
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Trying to access resource conv1/kernel located in device /job:localhost/replica:0/task:0/device:GPU:0 from device /job:localhost/replica:0/task:0/device:CPU:0
	 [[Node: AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum = ResourceApplyMomentum[T=DT_FLOAT, use_locking=false, use_nesterov=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](AccumGradOptimizer/cond/Momentum/update_conv1/kernel/Read/ReadVariableOp/Switch/_4783, AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum/Switch:1, AccumGradOptimizer/cond/Momentum/update_conv1/kernel/ResourceApplyMomentum/Switch_1/_4785, AccumGradOptimizer/cond/ReadVariableOp, AccumGradOptimizer/cond/Momentum/momentum/_4787)]]

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7efd3b8c9da0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 686, in __del__
TypeError: 'NoneType' object is not callable


```

**Comment by ppwwyyxx** [comment]
There is not enough code to reproduce your issue. But it seems like you just need `config_proto.allow_soft_placement=True`.
