### ISSUE TITLE
Error during testing image2image model

### ISSUE THREAD

**Issue by Kdoing** [ppwwyyxx/tensorpack#456]
Hello, after training the model on the facades dataset and viewing the loss curves on tensorboard I am unable to test the model.

I run it using the following command: python  image2image.py --sample --data facades/test --load train_log/image2image

and I get the following error:

2017-10-27 16:56:26.850382: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open train_log/image2image: Failed precondition: train_log/image2image: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "image2image", line 243, in <module>
    sample(args.data, args.load)
  File "image2image.py", line 221, in sample
    pred = SimpleDatasetPredictor(pred, ds)
  File "/miniconda2/lib/python2.7/site-packages/tensorpack/predict/dataset.py", line 66, in __init__
    self.predictor = OfflinePredictor(config)
  File "/miniconda2/lib/python2.7/site-packages/tensorpack/predict/base.py", line 166, in __init__
    config.session_init._setup_graph()
  File "/miniconda2/lib/python2.7/site-packages/tensorpack/tfutils/sessinit.py", line 112, in _setup_graph
    dic = self._get_restore_dict()
  File "/miniconda2/lib/python2.7/site-packages/tensorpack/tfutils/sessinit.py", line 161, in _get_restore_dict
    self._match_vars(f)
  File "/miniconda2/lib/python2.7/site-packages/tensorpack/tfutils/sessinit.py", line 128, in _match_vars
    reader, chkpt_vars = SaverRestore._read_checkpoint_vars(self.path)
  File "/miniconda2/lib/python2.7/site-packages/tensorpack/tfutils/sessinit.py", line 122, in _read_checkpoint_vars
    reader = tf.train.NewCheckpointReader(model_path)
  File "/miniconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/miniconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file train_log/WGAN-GP-pix2pix: Failed precondition: train_log/image2image: perhaps your file is in a different file format and you need to use a different restore operator?

Any help would be much appreciated !

**Comment by ppwwyyxx** [comment]
`--load` a model file, not the directory.
