### ISSUE TITLE
Regarding mnist-visualizations.py

### ISSUE THREAD

**Issue by loswensiana** [ppwwyyxx/tensorpack#462]
I just installed tensorpack, and run several example codes.

mnist-convnet.py and mnist-keras.py is executed successfully.

But when I run mnist-visualizations.py, error shown below occurs.

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: fc0/W/rms/_243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_87_fc0/W/rms", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Here are my logs when running mnist-visualizations.py

Could you please solve this issue?

[1101 15:31:03 @base.py:172] Initializing the session ...
[1101 15:31:03 @base.py:179] Graph Finalized.
[1101 15:31:03 @base.py:196] Start Epoch 1 ...
 93%|#########################################################################################################################################################################################9               |433/468[00:03<00:00,52.72it/s]2017-11-01 15:31:08.052607: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.052787: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053128: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053237: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053401: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053512: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053594: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053671: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053759: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.053833: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.054991: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.055057: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.055120: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.055178: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.055234: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.055298: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056440: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056495: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056532: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056564: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056597: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056628: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056661: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056691: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.056954: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.058530: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.058588: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.058821: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.059624: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.059882: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.059988: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.060283: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
2017-11-01 15:31:08.060331: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
100%|#######################################################################################################################################################################################################5|467/468[00:04<00:00,114.30it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: fc0/W/rms/_243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_87_fc0/W/rms", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist-visualizations.py", line 164, in <module>
    launch_train_with_config(config, SimpleTrainer())
  File "/usr/local/lib/python3.6/site-packages/tensorpack/trainv1/interface.py", line 11, in launch_train_with_config
    old_launch(config, trainer)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/train/interface.py", line 92, in launch_train_with_config
    config.steps_per_epoch, config.starting_epoch, config.max_epoch)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/train/base.py", line 238, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/train/base.py", line 202, in main_loop
 File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: fc0/W/rms/_243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_87_fc0/W/rms", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'input_1', defined at:
  File "mnist-visualizations.py", line 164, in <module>
    launch_train_with_config(config, SimpleTrainer())
 File "/usr/local/lib/python3.6/site-packages/tensorpack/trainv1/interface.py", line 11, in launch_train_with_config
    old_launch(config, trainer)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/train/interface.py", line 92, in launch_train_with_config
    config.steps_per_epoch, config.starting_epoch, config.max_epoch)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/train/base.py", line 236, in train
    self.setup_callbacks(callbacks, monitors)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/train/base.py", line 154, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/usr/local/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 53, in setup_graph
    self._setup_graph()
  File "/usr/local/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 64, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 53, in setup_graph
    self._setup_graph()
  File "/usr/local/lib/python3.6/site-packages/tensorpack/callbacks/inference_runner.py", line 132, in _setup_graph
    input_callbacks = self._input_source.setup(self.trainer.inputs_desc)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/input_source/input_source_base.py", line 97, in setup
    self._setup(inputs_desc)
  File "/usr/local/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 90, in _setup
    self._all_placehdrs = [v.build_placeholder(prefix='') for v in inputs]
  File "/usr/local/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 90, in <listcomp>
    self._all_placehdrs = [v.build_placeholder(prefix='') for v in inputs]
  File "/usr/local/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 53, in build_placeholder
    name=prefix + self.name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2094, in _placeholder
    name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: fc0/W/rms/_243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_87_fc0/W/rms", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by ppwwyyxx** [comment]
Thanks a lot!
