### ISSUE TITLE
How to evaluate trained Faster R-CNN model? 

### ISSUE THREAD

**Issue by BichenWuUCB** [ppwwyyxx/tensorpack#464]
Hi,

Thanks for adding the Faster-RCNN multi-gpu example. I'm wondering how to evaluate the trained model? I tried to load the model checkpoint as:

```
cd $FASTER_RCNN_EXAMPLE_DIR
./train.py --load train_log/fastrcnn/model-6000 --evaluate out.json
```

But I got the following error message:

```Traceback (most recent call last):
  File "./train.py", line 270, in <module>
    offline_evaluate(args.load, args.evaluate)
  File "./train.py", line 194, in offline_evaluate
    'fastrcnn_fg_boxes',
  File "/rscratch18/bichen/Proj/FRCN/frcn-tf/local/lib/python2.7/site-packages/tensorpack/predict/base.py", line 161, in __init__
    config.tower_func(*input.get_input_tensors())
  File "/rscratch18/bichen/Proj/FRCN/frcn-tf/local/lib/python2.7/site-packages/tensorpack/tfutils/tower.py", line 150, in __exit__
    self._name) + ', '.join([k.name for k in diff_trainable_vars])
AssertionError: New TRAINABLE_VARIABLES shouldn't be created in : conv0/W:0, conv0/bn/beta:0, conv0/bn/gamma:0  ... 
```
Any suggestions?

**Comment by BichenWuUCB** [comment]
Hi Yuxin,

Yes, upgrading to the latest master solved this problem. Thanks, and great work!
