### ISSUE TITLE
ImportError: cannot import name TOWER_FREEZE_KEYS

### ISSUE THREAD

**Issue by adeagle** [ppwwyyxx/tensorpack#477]
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> print tensorflow.__version__
1.4.0-rc1
>>> 

root@dl-1080:/data/TensorFlow/tensorpack/examples/ShuffleNet# python shufflenet.py 
Failed to load OpenCL runtime (expected version 1.1+)
Traceback (most recent call last):
  File "shufflenet.py", line 14, in <module>
    from tensorpack import logger, QueueInput, InputDesc, PlaceholderInput, TowerContext
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.7.1-py2.7.egg/tensorpack/__init__.py", line 16, in <module>
    from tensorpack.callbacks import *
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.7.1-py2.7.egg/tensorpack/callbacks/__init__.py", line 30, in <module>
    _global_import(module_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.7.1-py2.7.egg/tensorpack/callbacks/__init__.py", line 13, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.7.1-py2.7.egg/tensorpack/callbacks/inference_runner.py", line 22, in <module>
    from ..graph_builder.predict import SimplePredictBuilder
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.7.1-py2.7.egg/tensorpack/graph_builder/__init__.py", line 32, in <module>
    global_import(module_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.7.1-py2.7.egg/tensorpack/graph_builder/__init__.py", line 13, in global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.7.1-py2.7.egg/tensorpack/graph_builder/predictor_factory.py", line 10, in <module>
    from ..utils.naming import TOWER_FREEZE_KEYS
ImportError: cannot import name TOWER_FREEZE_KEYS

**Comment by adeagle** [comment]
pip uninstall tensorpack
python setup.py install

problem solved!!
