### ISSUE TITLE
ImportError: cannot import name 'disable_layer_logging'

### ISSUE THREAD

**Issue by vqdang** [ppwwyyxx/tensorpack#483]
As the title implies, It happened when I tried to use MultiProcessDatasetPredictor.

```
Traceback (most recent call last):
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/predict/concurrency.py", line 68, in run
    self._init_runtime()
  File "/home/vqdang/tools/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorpack/predict/concurrency.py", line 40, in _init_runtime
    from tensorpack.models.common import disable_layer_logging
ImportError: cannot import name 'disable_layer_logging'
```

**Comment by ppwwyyxx** [comment]
btw, `MultiProcessDatasetPredictor` doesn't scale very well. Doing inference is not a focus of the library and everything that predicts offline in tensorpack are `feed_dict` based and not well optimized.
