### ISSUE TITLE
Can't kill SyncMultiGPUTrainerParameterServer

### ISSUE THREAD

**Issue by dyelax** [ppwwyyxx/tensorpack#516]
I'm training a model with `SyncMultiGPUTrainerParameterServer` on multiple GPUs, but when I try to kill it early with ctrl-c, I see the following,

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/callbacks/prof.py", line 87, in worker
    time.sleep(1)
KeyboardInterrupt
```

And the program just hangs instead of terminating.

**Comment by ppwwyyxx** [comment]
This seems to be a side effect of the GPU utilization tracker callback. Should be fixed in the latest commit.
