### ISSUE TITLE
Mask/FastRCNN train error (resnet101)

### ISSUE THREAD

**Issue by jwnsu** [ppwwyyxx/tensorpack#536]
Same setup trained fine with ResNet50 (Mask_flag is False) about 4 days ago (ubuntu 16.04 with 8  GPUs) -- reached 0.36 (coco) mAP, great work & result!

Pulled latest codes moments ago and trying ResNet101 MastRCNN training, got following error:
" File "./train.py", line 405, in <module>
    launch_train_with_config(cfg, trainer)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/trainv1/interface.py", line 11, in launch_train_with_config
    old_launch(config, trainer)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/interface.py", line 88, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/tower.py", line 137, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/trainers.py", line 130, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 188, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 95, in build_on_towers
    ret.append(func())
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/tower.py", line 166, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/tfutils/tower.py", line 199, in __call__
    output = self._tower_fn(*args)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/model_desc.py", line 174, in _build_graph_get_cost
    self.build_graph(*inputs)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/graph_builder/model_desc.py", line 122, in build_graph
    self._build_graph(inputs)
  File "./train.py", line 169, in _build_graph
    mask_logits = maskrcnn_head('maskrcnn', fg_feature, config.NUM_CLASS)   # #fg x #cat x 14x14
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/dsu/ai/tfpack/examples/FasterRCNN/model.py", line 507, in maskrcnn_head
    l = Deconv2D('deconv', feature, 256, 2, stride=2, nl=tf.nn.relu)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/models/conv2d.py", line 114, in Deconv2D
    assert in_channel is not None, "[Deconv2D] Input cannot have unknown channel!"
AssertionError: [Deconv2D] Input cannot have unknown channel!"

Last few lines from log.log file suggested last channel is None, which is probably the cause for the error:"
^[[32m[1201 18:16:58 @registry.py:121]^[[0m fastrcnn input: [None, None, 7, 2048]
^[[32m[1201 18:16:58 @registry.py:121]^[[0m fastrcnn/gap input: [None, None, 7, 2048]
^[[32m[1201 18:16:58 @registry.py:129]^[[0m fastrcnn/gap output: [None, 2048]
^[[32m[1201 18:16:58 @registry.py:121]^[[0m fastrcnn/class input: [None, 2048]
^[[32m[1201 18:16:58 @registry.py:129]^[[0m fastrcnn/class output: [None, 40]
^[[32m[1201 18:16:58 @registry.py:121]^[[0m fastrcnn/box input: [None, 2048]
^[[32m[1201 18:16:58 @registry.py:129]^[[0m fastrcnn/box output: [None, 156]
^[[32m[1201 18:16:58 @registry.py:129]^[[0m fastrcnn output: [None, 40],[None, 39, 4]
^[[32m[1201 18:16:58 @registry.py:121]^[[0m maskrcnn input: [None, None, 7, None]
^[[32m[1201 18:16:58 @registry.py:121]^[[0m maskrcnn/deconv input: [None, None, 7, None]"

Resnet50 has same error.

Any suggestion?

**Comment by ppwwyyxx** [comment]
Things work fine on my side. By "pulled latest code" do you mean you update __both__ tensorpack and fasterrcnn? From the log they are located in different directories.

Older examples will run with new tensorpack - that's back-compatibility. But newer examples don't necessarily run with old tensorpack.

**Comment by jwnsu** [comment]
Forgot to updated tensorpack, just updated (install update) to latest tensorpack 0.8 (from 0.7.1), still got the same error. Also I made change to NHWC (so it could run inference on CPU-only). Will do a fresh repository pull to see whether it's fine.

**Comment by ppwwyyxx** [comment]
Oh.. if you made changes you should tell.
The code is written for NCHW. To work for NHWC you need to do more than global string replace.

**Comment by jwnsu** [comment]
Yeah, I simply did global replacement and commented out transpose in train.py. Let me revert back to clean repository to see if the issue disappears. Thx for quick comment.

**Comment by jwnsu** [comment]
After reverted NHWC changes, it now starting normal training. So the error was from NHWC changes.

Any plan to add NHWC support in tensorpack? Most of frameworks support test/inference on CPU.

Another question is on data augmentation. Some dataset needs to turn off flip (in data.py: "imgaug.Flip(horiz=True)"). However, after turn-off flip, there's an error from tensorpack that one of vertical or horiz needs to be on).

Will close the issue shortly.

**Comment by ppwwyyxx** [comment]
> Any plan to add NHWC support in tensorpack? Most of frameworks support test/inference on CPU.

tensorpack supports NHWC because it doesn't care what your model is at all. But you'll always need to implement NHWC version of fasterrcnn which I don't plan to do.

You can just remove the line `imgaug.Flip(horiz=True)`

**Comment by jwnsu** [comment]
After remove that line, training aborted with an error complaining either vertical or horiz needs to be on.

**Comment by ppwwyyxx** [comment]
It's impossible.

I said remove `imgaug.Flip(horiz=True)`.

**Comment by jwnsu** [comment]
That was exactly what I did a few days ago. Anyway, will try again.

**Comment by jwnsu** [comment]
Here is the error after set Horiz flip to false in data.py:
---
Traceback (most recent call last):
  File "./train.py", line 384, in <module>
    data=QueueInput(get_train_dataflow(add_mask=config.MODE_MASK)),
  File "/home/dsu/ai/tfpack/examples/FasterRCNN/data.py", line 205, in get_train_dataflow
    imgaug.Flip(horiz=False)]) #True
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/dataflow/imgaug/misc.py", line 35, in __init__
    raise ValueError("At least one of horiz or vert has to be True!")
ValueError: At least one of horiz or vert has to be True!
----

**Comment by jwnsu** [comment]
confirmed it works fine by simply removing it, by default tensorpack has the flag as false, thx for the info.
