### ISSUE TITLE
Watching the agent play fails

### ISSUE THREAD

**Issue by Zarnluz** [ppwwyyxx/tensorpack#558]
Hey there,

I am pretty new to Ubuntu and openai/gym so it might be a small problem.

I tried using the example you gave with the "./train-atari.py --task play --env Breakout-v0 --load Breakout-v0.npy" command yet it doesn't work.
I have downloaded the model and just wanted to watch it but I have a problem with the render I guess.

Here is my log:

Failed to load OpenCL runtime
[1217 15:17:12 @train-atari.py:283] Environment Name: Breakout-v0
[2017-12-17 15:17:12,833] Making new env: Breakout-v0
[1217 15:17:13 @train-atari.py:285] Number of actions: 4
[1217 15:17:13 @registry.py:121] conv0 input: [None, 84, 84, 12]
[1217 15:17:13 @registry.py:129] conv0 output: [None, 84, 84, 32]
[1217 15:17:13 @registry.py:121] pool0 input: [None, 84, 84, 32]
[1217 15:17:13 @registry.py:129] pool0 output: [None, 42, 42, 32]
[1217 15:17:13 @registry.py:121] conv1 input: [None, 42, 42, 32]
[1217 15:17:13 @registry.py:129] conv1 output: [None, 42, 42, 32]
[1217 15:17:13 @registry.py:121] pool1 input: [None, 42, 42, 32]
[1217 15:17:13 @registry.py:129] pool1 output: [None, 21, 21, 32]
[1217 15:17:13 @registry.py:121] conv2 input: [None, 21, 21, 32]
[1217 15:17:13 @registry.py:129] conv2 output: [None, 21, 21, 64]
[1217 15:17:13 @registry.py:121] pool2 input: [None, 21, 21, 64]
[1217 15:17:13 @registry.py:129] pool2 output: [None, 10, 10, 64]
[1217 15:17:13 @registry.py:121] conv3 input: [None, 10, 10, 64]
[1217 15:17:13 @registry.py:129] conv3 output: [None, 10, 10, 64]
[1217 15:17:13 @registry.py:121] fc0 input: [None, 10, 10, 64]
[1217 15:17:13 @registry.py:129] fc0 output: [None, 512]
[1217 15:17:13 @registry.py:121] fc-pi input: [None, 512]
[1217 15:17:13 @registry.py:129] fc-pi output: [None, 4]
[1217 15:17:13 @registry.py:121] fc-v input: [None, 512]
[1217 15:17:13 @registry.py:129] fc-v output: [None, 1]
2017-12-17 15:17:13.317081: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
[1217 15:17:13 @sessinit.py:206] Variables to restore from dict: fc-v/b:0, conv0/b:0, conv0/W:0, fc0/W:0, conv2/W:0, conv3/b:0, prelu/alpha:0, fc-pi/b:0, conv3/W:0, fc-v/W:0, fc0/b:0, conv2/b:0, fc-pi/W:0, conv1/b:0, conv1/W:0
[1217 15:17:13 @sessinit.py:219] Restoring from dict ...
[2017-12-17 15:17:13,498] Making new env: Breakout-v0
[1217 15:17:13 @common.py:42] Start Playing ...
Traceback (most recent call last):
  File "./train-atari.py", line 299, in <module>
    args.episode, render=True)
  File "/home/patrick/tensorpack/examples/A3C-Gym/common.py", line 44, in play_n_episodes
    score = play_one_episode(player, predfunc, render=render)
  File "/home/patrick/tensorpack/examples/A3C-Gym/common.py", line 35, in play_one_episode
    env.render()
  File "/home/patrick/gym/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/patrick/gym/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/home/patrick/gym/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/patrick/gym/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/home/patrick/gym/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/patrick/gym/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/home/patrick/gym/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/patrick/gym/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/home/patrick/gym/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/patrick/gym/gym/envs/atari/atari_env.py", line 117, in _render
    from gym.envs.classic_control import rendering
  File "/home/patrick/gym/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1884, in <module>
    gl._create_shadow_window()
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 501, in __init__
    display = get_platform().get_default_display()
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1833, in get_default_display
    return pyglet.canvas.get_display()
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/home/patrick/.local/lib/python2.7/site-packages/pyglet/canvas/xlib.py", line 86, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

I am using the Ubuntu Windows store app and have installed opencv and pyglet, yet I get the error message.

I hope this is just a small issue and you can help me.

**Comment by ppwwyyxx** [comment]
I don't think pyglet display works on ubuntu windows.

**Comment by nikoliazekter** [comment]
ubuntu windows?

**Comment by ppwwyyxx** [comment]
> I am using the Ubuntu Windows store app and have installed opencv and pyglet, yet I get the error message.

I assume it means this? https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6

**Comment by Zarnluz** [comment]
Okay, thank you for your reply.
I have to find a workaround then.
