### ISSUE TITLE
CUDA out of memoery on testing

### ISSUE THREAD

**Issue by hao522** [ppwwyyxx/tensorpack#566]
I ran python ./train.py --predict test_data  --load ./models/COCO-ResNet50-MaskRCNN.npz 
on GTX1080TI with 11.5GB GPU memory to test the model,.
  CUDA OOM was reported.

2017-12-22 02:54:36.956667: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[1000,1024,28,28]
Traceback (most recent call last):
  File "./train.py", line 376, in <module>
    predict_by_folder(pred, args.predict, './results')
  File "./train.py", line 303, in predict_by_folder
    results = detect_one_image(img, pred_func)
  File "/root/jh1/projects/raw_git_repos/tensorpack/examples/FasterRCNN/eval.py", line 76, in detect_one_image
    boxes, probs, labels, masks = model_func(resized_img)
  File "/root/jh1/projects/raw_git_repos/tensorpack/tensorpack/predict/base.py", line 52, in __call__
    output = self._do_call(dp)
  File "/root/jh1/projects/raw_git_repos/tensorpack/tensorpack/predict/base.py", line 144, in _do_call
    return self._do_call_new(dp)
  File "/root/jh1/projects/raw_git_repos/tensorpack/tensorpack/predict/base.py", line 135, in _do_call_new
    return self._callable(*dp)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1176, in _generic_run
    return self.run(fetches, feed_dict=feed_dict, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1000,1024,28,28]
         [[Node: roi_align/crop_and_resize/transpose_1 = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](roi_align/crop_and_resize/CropAndResize, roi_align/crop_and_resize/transpose_1/perm)]]
         [[Node: fastrcnn_predictions/map/while/Reshape/_1747 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2701_fastrcnn_predictions/map/while/Reshape", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfastrcnn_predictions/map/while/non_max_suppression/iou_threshold/_1675)]]

**Comment by ppwwyyxx** [comment]
Make sure no other processes (e.g. Xorg) are running on GPUs.
Try different configuration, e.g. one mentioned in another issue: https://github.com/ppwwyyxx/tensorpack/issues/467#issuecomment-341592143
As a last resort, change `config.py` to produce fewer predictions. There is a comment about it.

**Comment by hao522** [comment]
I set 'TEST_POST_NMS_TOPK' option in config.py to 600, it worked in this way, thx
