### ISSUE TITLE
Got error when inference with model.build_graph

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#602]
I have trained a model with tensorpack and want to do inference with that model. The following is some test code:

```
model = Model() 
image = tf.placeholder(dtype=tf.float32,
                       shape=[1, 224, 224, 3],
                       name='input_image')
label = tf.placeholder(dtype=tf.int32,
                       shape=[1],
                       name='input_label')
model.build_graph(image, label)
```
 When I run the code, I got the following error:
```
Traceback (most recent call last):
  File "predict.py", line 47, in <module>
    predict(args)
  File "predict.py", line 27, in predict
    model.build_graph(image, label)
  File "/home/user/tensorpack/tensorpack/graph_builder/model_desc.py", line 114, in build_graph
    self._build_graph(inputs)
  File "/home/user/tensorpack/examples/ShuffleNet/imagenet_utils.py", line 158, in _build_graph
    logits = self.get_logits(image)
  File "/home/user/tensorpack/examples/ShuffleNet/test_model.py", line 42, in get_logits
    l = Conv2D('conv1', image, 16, 3, stride=2, nl=BNReLU)
  File "/home/user/tensorpack/tensorpack/models/registry.py", line 125, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/user/tensorpack/tensorpack/models/conv2d.py", line 74, in Conv2D
    ret = nl(tf.nn.bias_add(conv, b, data_format=data_format) if use_bias else conv, name='output')
  File "/home/user/tensorpack/tensorpack/models/registry.py", line 134, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/user/tensorpack/tensorpack/models/nonlin.py", line 84, in BNReLU
    x = BatchNorm('bn', x)
  File "/home/user/tensorpack/tensorpack/models/registry.py", line 125, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/user/tensorpack/tensorpack/models/batch_norm.py", line 126, in BatchNorm
    use_local_stat = ctx.is_training
AttributeError: 'NoneType' object has no attribute 'is_training'
```
I used BatchNorm in the model, and error is caused that the `get_current_tower_context()` called in BatchNorm returned None. How can I avoid this error?

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/en/latest/tutorial/symbolic.html#use-models-outside-tensorpack

**Comment by JesseYang** [comment]
Thanks!
