### ISSUE TITLE
DataFlow is not reentrant!

### ISSUE THREAD

**Issue by sagarwaghmare69** [ppwwyyxx/tensorpack#604]
A sample dataflow returning 4 items (img, target_array1, target_array2, target_array3).

    train_ds = MyDataFlow()
    train_ds = AugmentImageComponent(train_ds, augmentors_train,
                                     index=0, copy=False)

    train_ds = PrefetchDataZMQ(train_ds, n_procs)
    train_ds = BatchData(train_ds, batch, use_list=True)
    train_ds1 = SelectComponent(train_ds, [0, 1, 2])
    train_ds2 = SelectComponent(train_ds, [3])
    # Need target_array3 as np.float32 array
    train_ds2 = MapData(train_bbox_ds,
                            lambda dp: np.stack(dp, 0).astype(np.float32))
    train_ds = JoinData([train_ds1, train_ds1])

I tested the final dataflow without PrefetchDataZMQ and it works fine though slow. With PrefetchDataZMQ I get following error

1) for inputs in train_ds.get_data(): 
        break
    OR
    train_ds.reset_state()
    for inputs in train_ds.get_data(): 
        break
RuntimeError: This DataFlow is not reentrant!

2) When using launch_train_with_config
[0122 13:14:08 @input_source.py:142] ERR Exception in EnqueueThread QueueInput/input_queue:
Traceback (most recent call last):
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 132, in run
    dp = next(self._itr)
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 329, in get_data
    for dp in self.ds.get_data():
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 511, in get_data
    dp.extend(next(itr))
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 265, in get_data
    for dp in self.ds.get_data():
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 265, in get_data
    for dp in self.ds.get_data():
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 107, in get_data
    for data in self.ds.get_data():
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 284, in get_data
    with self._guard, _zmq_catch_error('PrefetchDataZMQ'):
  File "/home/swaghmare/.virtualenvs/keras2/lib/python3.6/site-packages/tensorpack/dataflow/base.py", line 36, in __enter__
    raise threading.ThreadError("This DataFlow is not reentrant!")
RuntimeError: This DataFlow is not reentrant!

Any help is appreciated. Kind regards.

**Comment by ppwwyyxx** [comment]
You used this dataflow instance: `train_ds = BatchData(train_ds, batch, use_list=True)` twice and that's not allowed for `PrefetchDataZMQ`.
You should either create two dataflow instances or not use `PrefetchDataZMQ`.

**Comment by sagarwaghmare69** [comment]
Thank you for quick response. When you say not use PrefetchDataZMQ does that mean any of the parallel dataflows ? 
I will try to redesign the whole flow to avoid using train_ds = BatchData(train_ds, batch, use_list=True) twice.

**Comment by ppwwyyxx** [comment]
Most parallel dataflows do not support this, and even if some do, it may not work the same way you may expect. For example, MultiThreadPrefetchData can be used twice, but each data point from it will only go to one of the two but not both of them. In general it's best to not use it twice to avoid confusion.

**Comment by sagarwaghmare69** [comment]
Ok, cool. Thank you very much for your help.
