### ISSUE TITLE
GAN examples don't work

### ISSUE THREAD

**Issue by leix28** [ppwwyyxx/tensorpack#619]
I tried DCGAN.py and Image2Image.py with default dataset. 

I ran into the same type assertion errors.

```
Traceback (most recent call last):
  File "DCGAN.py", line 162, in <module>
    model=Model()).train_with_defaults(
  File "/Users/leonardxu/studio/GAN/GAN.py", line 73, in __init__
    self.register_callback(cbs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorpack/train/base.py", line 112, in _register_callback
    assert isinstance(cb, Callback), cb
AssertionError: [<tensorpack.callbacks.base.CallbackFactory object at 0x1304094e0>, <tensorpack.callbacks.concurrency.StartProcOrThread object at 0x130409400>, <tensorpack.callbacks.graph.RunOp object at 0x12d829358>, <tensorpack.callbacks.base.CallbackFactory object at 0x1304090f0>]
```

package version

```
tensorflow (1.4.0)
tensorpack (0.8.0)
```

**Comment by ppwwyyxx** [comment]
Install tensorpack by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`.

**Comment by leix28** [comment]
It works. Thank you!
