### ISSUE TITLE
PrefetchData cause TypeError: can't pickle Environment objects

### ISSUE THREAD

**Issue by jumpapex** [ppwwyyxx/tensorpack#621]
Dear sir,

I just do some test to write and read a lmdb file.
After i prepare the go_train.lmdb

then i use the following code to do a benchmark

        df = LMDBDataPoint(args.lmdb + 'go_train.lmdb', shuffle=False)
        df = PrefetchData(df, 5000, 1)
        df = GameDecoder(df, verbose=False)
        df = PrefetchDataZMQ(df, min(20, multiprocessing.cpu_count()))
        df.reset_state()
        TestDataSpeed(df, size=50000).start_test()

the result:
[0202 11:08:07 @format.py:86] Found 75049 entries in D:\Go\Go\godb\go_train.lmdb
Traceback (most recent call last):
  File "D:/Go/Go/go_db.py", line 198, in <module>
    df = PrefetchData(df, 5000, 1)
  File "C:\Python\Python36\lib\site-packages\tensorpack\dataflow\parallel.py", line 185, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\Python\Python36\lib\site-packages\tensorpack\utils\concurrency.py", line 212, in start_proc_mask_signal
    p.start()
  File "C:\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
**TypeError: can't pickle Environment objects**

OS: Windows 10 64bit
Python: 3.6.4 64 bit
Tensorpack 0.8.1

Could you pls give me some hint for the error?
BTW, running example mnist_convnet.py is OK.

Regards!
Jumpapex

**Comment by ppwwyyxx** [comment]
This is a Python issue. Python pickle has limitations on what type of objects it supports. You need to design you `GameDecoder` so that it doesn't include such objects.
