### ISSUE TITLE
Debug with tf_debug.LocalCLIDebugWrapperSession

### ISSUE THREAD

**Issue by MrWanter** [ppwwyyxx/tensorpack#631]
I cloned shufflenet example, my code runs properly without change, but when I add debug according to 
https://github.com/ppwwyyxx/tensorpack/issues/191, I use the first one, that is 
```
SessionCreatorAdapter(NewSessionCreator(), 
    lambda sess: tf_debug.LocalCLIDebugWrapperSession(sess, other_options))
```
and pass s into the trainconfig:
```
    creator = SessionCreatorAdapter(NewSessionCreator(),
         lambda sess: tf_debug.LocalCLIDebugWrapperSession(sess))

    return TrainConfig(
        session_creator=creator,
        model=model,
        dataflow=dataset_train,
        callbacks=callbacks,
        steps_per_epoch=5000,
        max_epoch=100,
    )
```
but I got the following error:
```
Traceback (most recent call last):
  File "/home/user/.pycharm_helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/prj/shufflenet_v1/shufflenet.py", line 231, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_tower))
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/interface.py", line 96, in launch_train_with_config
    config.steps_per_epoch, config.starting_epoch, config.max_epoch)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 288, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 239, in main_loop
    self.loop.update_global_step()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 59, in update_global_step
    self._global_step = get_global_step_value()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/tfutils/common.py", line 77, in get_global_step_value
    get_global_step_var())
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/training_util.py", line 67, in global_step
    return int(sess.run(global_step_tensor))
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/wrappers/framework.py", line 455, in run
    is_callable_runner=bool(callable_runner)))
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 253, in on_run_start
    self._prep_cli_for_run_start()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 275, in _prep_cli_for_run_start
    self._run_cli = ui_factory.get_ui(self._ui_type)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/ui_factory.py", line 56, in get_ui
    return curses_ui.CursesUI(on_ui_exit=on_ui_exit)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 285, in __init__
    self._screen_init()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 400, in _screen_init
    self._screen_color_init()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 405, in _screen_color_init
    curses.use_default_colors()
error: use_default_colors() returned ERR
```
I tried adding hook method as mentioned in https://github.com/ppwwyyxx/tensorpack/issues/191, but same error prompts

**Comment by MrWanter** [comment]
I was using the `shufflenet` example in `pycharm` remote interpreter, tried in terminal with hook, it can launch the `tfdbg`, but when I execute `run`, following error prompts:
```
2018-02-06 20:10:57.294184: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad/ShapeN:0:DebugIdentityfailed to publish debug tensor data to all URLs file:///tmp/tfdbg_GaHK48, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad, due to: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
2018-02-06 20:10:57.294370: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad/ShapeN:1:DebugIdentityfailed to publish debug tensor data to all URLs file:///tmp/tfdbg_GaHK48, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad, due to: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
2018-02-06 20:10:57.294561: F tensorflow/core/debug/debug_io_utils.cc:625] Non-OK-status: f->Close() status: Resource exhausted: /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_2/tower2/gradients/tower2/group2/block2/add_grad/Shape_1_0_DebugIdentity_1517919057294193; No space left on device
2018-02-06 20:10:57.294858: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad/ShapeN:0:DebugIdentityfailed to publish debug tensor data to all URLs file:///tmp/tfdbg_GaHK48, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad, due to: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
2018-02-06 20:10:57.295052: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad/ShapeN:1:DebugIdentityfailed to publish debug tensor data to all URLs file:///tmp/tfdbg_GaHK48, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad, due to: Failed to create directory  /tmp/tfdbg_GaHK48/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
```

**Comment by ppwwyyxx** [comment]
Tensorflow requires you to run tfdebug inside a valid normal terminal.

**Comment by MrWanter** [comment]
Yes, when I tried on terminal, it works fine, but seems when I get a `tfdbg -> run`, it dumps so many things out, then root directory is filled, before run, there is 11G left, with a run, prompts no space left:
```
2018-02-07 10:23:07.433343: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/add_grad/Shape:0:DebugIdentityfailed to publish debug tensor data to all URLs file:///var/tmp/tfdbg_2DnmZj, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/add_grad, due to: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3;
2018-02-07 10:23:07.443635: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad/ShapeN:0:DebugIdentityfailed to publish debug tensor data to all URLs file:///var/tmp/tfdbg_2DnmZj, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad, due to: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
2018-02-07 10:23:07.443804: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad/ShapeN:1:DebugIdentityfailed to publish debug tensor data to all URLs file:///var/tmp/tfdbg_2DnmZj, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_2_grad, due to: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
2018-02-07 10:23:07.445778: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad/ShapeN:0:DebugIdentityfailed to publish debug tensor data to all URLs file:///var/tmp/tfdbg_2DnmZj, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad, due to: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
2018-02-07 10:23:07.445894: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad/ShapeN:1:DebugIdentityfailed to publish debug tensor data to all URLs file:///var/tmp/tfdbg_2DnmZj, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_1_grad, due to: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
2018-02-07 10:23:07.446192: E ./tensorflow/core/kernels/debug_ops.h:186] Debug node of watch key tower1/gradients/tower1/group2/block3/conv1/Conv2D_grad/ShapeN:0:DebugIdentityfailed to publish debug tensor data to all URLs file:///var/tmp/tfdbg_2DnmZj, due to: Publishing to 1 of 1 debug target URLs failed, due to the following errors: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1/Conv2D_grad, due to: Failed to create directory  /var/tmp/tfdbg_2DnmZj/_tfdbg_device_,job_localhost,replica_0,task_0,device_GPU_1/tower1/gradients/tower1/group2/block3/conv1;
```
Have you  tried this?

**Comment by ppwwyyxx** [comment]
From what I can see this is just how tfdbg works.

**Comment by ppwwyyxx** [comment]
To future users: the best way to use `tfdbg` is to add this callback to your training callbacks:
```
callbacks=[
    ...,
    TFLocalCLIDebugHook()
]
```
See docs at: https://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.TFLocalCLIDebugHook

The tfdbg session wrapper will not work with tensorpack callbacks - this is a tensorflow bug. Don't use the session wrapper.
