### ISSUE TITLE
crash on tensorflow r0.12 rc 0

### ISSUE THREAD

**Issue by ahundt** [ppwwyyxx/tensorpack#64]
It seems the histogram api will be changing slightly with the new [tensorflow r0.12](https://github.com/tensorflow/tensorflow/tree/r0.12):

```
± ./train-atari.py --env Breakout-v0 --gpu 0
[...snip...]
[1207 23:57:42 @_common.py:80] fc-v output: [None, 1]
Traceback (most recent call last):
  File "./train-atari.py", line 259, in <module>
    AsyncMultiGPUTrainer(config, predict_tower=predict_tower).train()
  File "/home/ahundt/src/tensorpack/tensorpack/train/base.py", line 58, in train
    self.setup()
  File "/home/ahundt/src/tensorpack/tensorpack/train/base.py", line 103, in setup
    self._setup()
  File "/home/ahundt/src/tensorpack/tensorpack/train/multigpu.py", line 123, in _setup
    grad_list = [apply_grad_processors(g, gradprocs) for g in grad_list]
  File "/home/ahundt/src/tensorpack/tensorpack/tfutils/gradproc.py", line 31, in apply_grad_processors
    g = proc.process(g)
  File "/home/ahundt/src/tensorpack/tensorpack/tfutils/gradproc.py", line 45, in process
    return self._process(grads)
  File "/home/ahundt/src/tensorpack/tensorpack/tfutils/gradproc.py", line 93, in _process
    grad = self.func(grad, var)
  File "/home/ahundt/src/tensorpack/tensorpack/tfutils/gradproc.py", line 113, in _mapper
    tf.summary.histogram(name + '-grad', grad)
AttributeError: 'module' object has no attribute 'histogram'
```

**Comment by ppwwyyxx** [comment]
`tf.summary.histogram` is added very recently. I think you're actually not using r0.12rc0. Could you double check your version?

**Comment by ahundt** [comment]
@ppwwyyxx you're right, I ran an r0.12 install script but it doesn't seem to have worked correctly. Thanks! Will reopen if the problem remains after updating

**Comment by ahundt** [comment]
I forgot to run the pip install step. :-)
