### ISSUE TITLE
issue about DoReFA.     AttributeError: 'module' object has no attribute 'fused_batch_norm'?

### ISSUE THREAD

**Issue by silverlining21** [ppwwyyxx/tensorpack#67]
@ppwwyyxx 你好，你们的DoReFa-net很nice！

`我在采用你公布的代码跑实验的时候遇到如下问题发现。我采用的tensorflow版本是**0.11**，代码中你建议的版本是>=0.11.下来我去查看了tensorflow API 

**r0.11**没有找到 fused_batch_norm
[https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#neural-network](url)

**master**找到了函数fused_batch_norm
[https://www.tensorflow.org/versions/master/api_docs/python/nn.html#fused_batch_norm](url)

所以我想请问一下你的代码是基于 **master 分支**来时实现的吗？ 针对这个问题除了重装TF，有没有其他的什么解决办法呢？ 打搅了，祝好！

> 
```
nrp@scs4450-SYS-7048GR-TR:~/program/tensorpack/examples/DoReFa-Net$ python idcard-dorefa.py --dorefa 1,2,6 --data /home/nrp/data/idcard --gpu 0
[1215 15:51:54 @idcard-dorefa.py:307] Batch per tower: 128
[1215 15:51:54 @logger.py:69] WRN Directory train_log/idcard-dorefa exists! Please either backup/delete it, or use a new directory.
[1215 15:51:54 @logger.py:71] WRN If you're resuming from a previous run you can choose to keep it.
[1215 15:51:54 @logger.py:72] Select Action: k (keep) / b (backup) / d (delete) / n (new):
d
[1215 15:51:56 @logger.py:57] Argv: idcard-dorefa.py --dorefa 1,2,6 --data /home/nrp/data/idcard --gpu 0
[1215 15:51:56 @utils.py:60] TENSORPACK_DATASET not set, using /home/nrp/program/tensorpack/tensorpack/dataflow/dataset for dataset.
[1215 15:51:59 @multigpu.py:27] Training a model of 1 tower
[1215 15:51:59 @multigpu.py:35] Building graph for training tower 0...
[1215 15:51:59 @_common.py:72] conv0 input: [None, 32, 32, 3]
[1215 15:51:59 @_common.py:80] conv0 output: [None, 6, 6, 96]
[1215 15:51:59 @_common.py:72] conv1 input: [None, 6, 6, 96]
[1215 15:51:59 @idcard-dorefa.py:90] Binarizing weight conv1/W
[1215 15:51:59 @_common.py:80] conv1 output: [None, 6, 6, 256]
Traceback (most recent call last):
  File "idcard-dorefa.py", line 314, in <module>
    SyncMultiGPUTrainer(config).train()
  File "/home/nrp/program/tensorpack/tensorpack/train/base.py", line 58, in train
    self.setup()
  File "/home/nrp/program/tensorpack/tensorpack/train/base.py", line 106, in setup
    self._setup()
  File "/home/nrp/program/tensorpack/tensorpack/train/multigpu.py", line 86, in _setup
    self.config.tower, lambda: self._get_cost_and_grad()[1])
  File "/home/nrp/program/tensorpack/tensorpack/train/multigpu.py", line 37, in _multi_tower_grads
    grad_list.append(get_tower_grad_func())
  File "/home/nrp/program/tensorpack/tensorpack/train/multigpu.py", line 86, in <lambda>
    self.config.tower, lambda: self._get_cost_and_grad()[1])
  File "/home/nrp/program/tensorpack/tensorpack/train/trainer.py", line 134, in _get_cost_and_grad
    self.model.build_graph(actual_inputs)
  File "/home/nrp/program/tensorpack/tensorpack/models/model_desc.py", line 85, in build_graph
    self._build_graph(model_inputs)
  File "idcard-dorefa.py", line 109, in _build_graph
    .BatchNorm('bn1')
  File "/home/nrp/program/tensorpack/tensorpack/models/__init__.py", line 56, in f
    ret = layer(name, self._t, *args, **kwargs)
  File "/home/nrp/program/tensorpack/tensorpack/models/_common.py", line 75, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/nrp/program/tensorpack/tensorpack/models/batch_norm.py", line 151, in BatchNormV2
    xn, batch_mean, batch_var = tf.nn.fused_batch_norm(x, gamma, beta,
AttributeError: 'module' object has no attribute 'fused_batch_norm'
Prefetch process exited.
Prefetch process exited.

```
>

**Comment by ppwwyyxx** [comment]
I pushed a fix just now which uses an older version of BN when it couldn't find fused_batch_norm.
But still I'd suggest updating TensorFlow is possible.

**Comment by silverlining21** [comment]
太感谢了！

关于TF版本的问题，我也查看了**0.12**版本，也没有**fused_batch_norm**接口.
[https://www.tensorflow.org/versions/r0.12/api_docs/python/nn.html#neural-network](url)

**Comment by ppwwyyxx** [comment]
0.12 rc1是有的．应该是文档bug.
