### ISSUE TITLE
ERR Exception in EnqueueThread QueueInput/input_queue:

### ISSUE THREAD

**Issue by souxun2015** [ppwwyyxx/tensorpack#681]
I try imagenet-resnet.py following the instructions. But I get some errors.
`[0301 09:29:21 @logger.py:102] WRN Log directory train_log/imagenet-resnet-d18 exists! Use 'd' to delete it. 
[0301 09:29:21 @logger.py:105] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.

Select Action: k (keep) / d (delete) / q (quit):d
[0301 09:29:24 @logger.py:74] Argv: /home/llx/Documents/tensorpack-master/examples/ResNet/imagenet-resnet.py
[0301 09:29:24 @imagenet-resnet.py:74] Running on 2 towers. Batch size per tower: 128
[0301 09:29:24 @fs.py:89] WRN Env var $TENSORPACK_DATASET not set, using /home/llx/tensorpack_data for datasets.
[0301 09:29:25 @imagenet_utils.py:102] WRN DataFlow may become the bottleneck when too few processes are used.
[0301 09:29:25 @parallel.py:282] [PrefetchDataZMQ] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0301 09:29:26 @ilsvrc.py:118] Assuming directory /media/llx/新加卷/Database/ImageNet2012/val has original structure.
[0301 09:29:26 @inference_runner.py:81] InferenceRunner will eval 391 iterations
[0301 09:29:26 @training.py:42] Training a model of 2 towers
[0301 09:29:26 @interface.py:32] Automatically applying QueueInput on the DataFlow.
[0301 09:29:26 @interface.py:43] Automatically applying StagingInput on the DataFlow.
[0301 09:29:26 @input_source.py:194] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0301 09:29:26 @training.py:106] Building graph for training tower 0 on device /gpu:0...
[0301 09:29:26 @registry.py:121] conv0 input: [None, 3, 224, 224]
[0301 09:29:26 @registry.py:129] conv0 output: [None, 64, 112, 112]
[0301 09:29:26 @registry.py:121] pool0 input: [None, 64, 112, 112]
[0301 09:29:26 @registry.py:129] pool0 output: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:121] group0/block0/conv1 input: [None, 64, 56, 56]
Traceback (most recent call last):
  File "/home/llx/anaconda2/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 76: ordinal not in range(128)
Logged from file ilsvrc.py, line 118
[0301 09:29:26 @registry.py:129] group0/block0/conv1 output: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:121] group0/block0/conv2 input: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:129] group0/block0/conv2 output: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:121] group0/block1/conv1 input: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:129] group0/block1/conv1 output: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:121] group0/block1/conv2 input: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:129] group0/block1/conv2 output: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:121] group1/block0/conv1 input: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:129] group1/block0/conv1 output: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:121] group1/block0/conv2 input: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:129] group1/block0/conv2 output: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:121] group1/block0/convshortcut input: [None, 64, 56, 56]
[0301 09:29:26 @registry.py:129] group1/block0/convshortcut output: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:121] group1/block1/conv1 input: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:129] group1/block1/conv1 output: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:121] group1/block1/conv2 input: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:129] group1/block1/conv2 output: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:121] group2/block0/conv1 input: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:129] group2/block0/conv1 output: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:121] group2/block0/conv2 input: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:129] group2/block0/conv2 output: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:121] group2/block0/convshortcut input: [None, 128, 28, 28]
[0301 09:29:26 @registry.py:129] group2/block0/convshortcut output: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:121] group2/block1/conv1 input: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:129] group2/block1/conv1 output: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:121] group2/block1/conv2 input: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:129] group2/block1/conv2 output: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:121] group3/block0/conv1 input: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:129] group3/block0/conv1 output: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:121] group3/block0/conv2 input: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:129] group3/block0/conv2 output: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:121] group3/block0/convshortcut input: [None, 256, 14, 14]
[0301 09:29:26 @registry.py:129] group3/block0/convshortcut output: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:121] group3/block1/conv1 input: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:129] group3/block1/conv1 output: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:121] group3/block1/conv2 input: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:129] group3/block1/conv2 output: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:121] gap input: [None, 512, 7, 7]
[0301 09:29:26 @registry.py:129] gap output: [None, 512]
[0301 09:29:26 @registry.py:121] linear input: [None, 512]
[0301 09:29:26 @registry.py:129] linear output: [None, 1000]
[0301 09:29:26 @regularize.py:81] regularize_cost() found 21 tensors.
[0301 09:29:26 @regularize.py:18] Applying regularizer for conv0/W:0, group0/block0/conv1/W:0, group0/block0/conv2/W:0, group0/block1/conv1/W:0, group0/block1/conv2/W:0, group1/block0/conv1/W:0, group1/block0/conv2/W:0, group1/block0/convshortcut/W:0, group1/block1/conv1/W:0, group1/block1/conv2/W:0, group2/block0/conv1/W:0, group2/block0/conv2/W:0, group2/block0/convshortcut/W:0, group2/block1/conv1/W:0, group2/block1/conv2/W:0, group3/block0/conv1/W:0, group3/block0/conv2/W:0, group3/block0/convshortcut/W:0, group3/block1/conv1/W:0, group3/block1/conv2/W:0, linear/W:0
[0301 09:29:27 @training.py:106] Building graph for training tower 1 on device /gpu:1...
[0301 09:29:27 @regularize.py:81] regularize_cost() found 21 tensors.
[0301 09:29:28 @training.py:278] 'sync_variables_from_main_tower' includes 164 operations.
[0301 09:29:28 @model_utils.py:49] Model Parameters:
name                                   shape                 dim
-------------------------------------  ----------------  -------
conv0/W:0                              [7, 7, 3, 64]        9408
conv0/bn/beta:0                        [64]                   64
conv0/bn/gamma:0                       [64]                   64
group0/block0/conv1/W:0                [3, 3, 64, 64]      36864
group0/block0/conv1/bn/beta:0          [64]                   64
group0/block0/conv1/bn/gamma:0         [64]                   64
group0/block0/conv2/W:0                [3, 3, 64, 64]      36864
group0/block0/conv2/bn/beta:0          [64]                   64
group0/block0/conv2/bn/gamma:0         [64]                   64
group0/block1/conv1/W:0                [3, 3, 64, 64]      36864
group0/block1/conv1/bn/beta:0          [64]                   64
group0/block1/conv1/bn/gamma:0         [64]                   64
group0/block1/conv2/W:0                [3, 3, 64, 64]      36864
group0/block1/conv2/bn/beta:0          [64]                   64
group0/block1/conv2/bn/gamma:0         [64]                   64
group1/block0/conv1/W:0                [3, 3, 64, 128]     73728
group1/block0/conv1/bn/beta:0          [128]                 128
group1/block0/conv1/bn/gamma:0         [128]                 128
group1/block0/conv2/W:0                [3, 3, 128, 128]   147456
group1/block0/conv2/bn/beta:0          [128]                 128
group1/block0/conv2/bn/gamma:0         [128]                 128
group1/block0/convshortcut/W:0         [1, 1, 64, 128]      8192
group1/block0/convshortcut/bn/beta:0   [128]                 128
group1/block0/convshortcut/bn/gamma:0  [128]                 128
group1/block1/conv1/W:0                [3, 3, 128, 128]   147456
group1/block1/conv1/bn/beta:0          [128]                 128
group1/block1/conv1/bn/gamma:0         [128]                 128
group1/block1/conv2/W:0                [3, 3, 128, 128]   147456
group1/block1/conv2/bn/beta:0          [128]                 128
group1/block1/conv2/bn/gamma:0         [128]                 128
group2/block0/conv1/W:0                [3, 3, 128, 256]   294912
group2/block0/conv1/bn/beta:0          [256]                 256
group2/block0/conv1/bn/gamma:0         [256]                 256
group2/block0/conv2/W:0                [3, 3, 256, 256]   589824
group2/block0/conv2/bn/beta:0          [256]                 256
group2/block0/conv2/bn/gamma:0         [256]                 256
group2/block0/convshortcut/W:0         [1, 1, 128, 256]    32768
group2/block0/convshortcut/bn/beta:0   [256]                 256
group2/block0/convshortcut/bn/gamma:0  [256]                 256
group2/block1/conv1/W:0                [3, 3, 256, 256]   589824
group2/block1/conv1/bn/beta:0          [256]                 256
group2/block1/conv1/bn/gamma:0         [256]                 256
group2/block1/conv2/W:0                [3, 3, 256, 256]   589824
group2/block1/conv2/bn/beta:0          [256]                 256
group2/block1/conv2/bn/gamma:0         [256]                 256
group3/block0/conv1/W:0                [3, 3, 256, 512]  1179648
group3/block0/conv1/bn/beta:0          [512]                 512
group3/block0/conv1/bn/gamma:0         [512]                 512
group3/block0/conv2/W:0                [3, 3, 512, 512]  2359296
group3/block0/conv2/bn/beta:0          [512]                 512
group3/block0/conv2/bn/gamma:0         [512]                 512
group3/block0/convshortcut/W:0         [1, 1, 256, 512]   131072
group3/block0/convshortcut/bn/beta:0   [512]                 512
group3/block0/convshortcut/bn/gamma:0  [512]                 512
group3/block1/conv1/W:0                [3, 3, 512, 512]  2359296
group3/block1/conv1/bn/beta:0          [512]                 512
group3/block1/conv1/bn/gamma:0         [512]                 512
group3/block1/conv2/W:0                [3, 3, 512, 512]  2359296
group3/block1/conv2/bn/beta:0          [512]                 512
group3/block1/conv2/bn/gamma:0         [512]                 512
linear/W:0                             [512, 1000]        512000
linear/b:0                             [1000]               1000
Total #vars=62, #params=11689512, size=44.59MB
[0301 09:29:28 @base.py:204] Setup callbacks graph ...
[0301 09:29:29 @input_source.py:194] Setting up the queue 'DataParallelInferenceRunner/QueueInput/input_queue' for CPU prefetching ...
[0301 09:29:29 @predict.py:42] Building predictor tower 'InferenceTower0' on device /gpu:0 ...
[0301 09:29:29 @predict.py:42] Building predictor tower 'InferenceTower1' on device /gpu:1 ...
[0301 09:29:29 @summary.py:34] Maintain moving average summary of 4 tensors.
[0301 09:29:29 @graph.py:90] Applying collection UPDATE_OPS of 40 ops.
[0301 09:29:30 @base.py:220] Creating the session ...
[0301 09:29:32 @base.py:228] Initializing the session ...
[0301 09:29:32 @base.py:235] Graph Finalized.
[0301 09:29:32 @concurrency.py:38] Starting EnqueueThread QueueInput/input_queue ...
[0301 09:29:32 @graph.py:72] Running Op sync_variables/sync_variables_from_main_tower ...
[0301 09:29:32 @input_source.py:143] ERR Exception in EnqueueThread QueueInput/input_queue:
Traceback (most recent call last):
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/input_source/input_source.py", line 133, in run
    dp = next(self._itr)
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/dataflow/common.py", line 338, in get_data
    for dp in self.ds.get_data():
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/dataflow/common.py", line 116, in get_data
    for data in self.ds.get_data():
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/dataflow/parallel.py", line 300, in get_data
    yield self._recv()
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/dataflow/parallel.py", line 290, in _recv
    return loads(self.socket.recv(copy=False).bytes)
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/utils/serialize.py", line 40, in loads_msgpack
    return msgpack.loads(buf, raw=False)
  File "/home/llx/anaconda2/lib/python2.7/site-packages/msgpack_numpy-0.4.3-py2.7.egg/msgpack_numpy.py", line 184, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 100, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:1777)
TypeError: unpackb() got an unexpected keyword argument 'raw'
[0301 09:29:32 @input_source.py:149] EnqueueThread QueueInput/input_queue Exited.
[0301 09:29:33 @concurrency.py:38] Starting EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue ...
[0301 09:29:33 @base.py:255] Start Epoch 1 ...
  0%|          |0/5000[00:00<?,?it/s][0301 09:29:33 @input_source.py:496] Pre-filling StagingArea ...
[0301 09:29:33 @base.py:271] Training was stopped.

[0301 09:29:33 @input_source.py:143] ERR Exception in EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue:
Traceback (most recent call last):
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/input_source/input_source.py", line 133, in run
    dp = next(self._itr)
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/dataflow/common.py", line 338, in get_data
    for dp in self.ds.get_data():
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/dataflow/parallel.py", line 300, in get_data
    yield self._recv()
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/dataflow/parallel.py", line 290, in _recv
    return loads(self.socket.recv(copy=False).bytes)
  File "/home/llx/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.1-py2.7.egg/tensorpack/utils/serialize.py", line 40, in loads_msgpack
    return msgpack.loads(buf, raw=False)
  File "/home/llx/anaconda2/lib/python2.7/site-packages/msgpack_numpy-0.4.3-py2.7.egg/msgpack_numpy.py", line 184, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 100, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:1777)
TypeError: unpackb() got an unexpected keyword argument 'raw'
[0301 09:29:33 @input_source.py:149] EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue Exited.`

**Comment by ppwwyyxx** [comment]
Upgrade msgpack

**Comment by souxun2015** [comment]
But my msgpack's version is 0.5.6
`Requirement already up-to-date: msgpack in ./anaconda2/lib/python2.7/site-packages/msgpack-0.5.6-py2.7-linux-x86_64.egg
`

**Comment by ppwwyyxx** [comment]
msgpack unpackb has the argument 'raw': https://github.com/msgpack/msgpack-python/commit/5569a4efcdc913d343eaff4e55c9b19fafde4268#diff-82bf3c7d2bf3fc852729c754ffa93870 

Maybe you have multiple msgpack installed in different places.

**Comment by ppwwyyxx** [comment]
Maybe you also need to uninstall msgpack-python first. See https://github.com/msgpack/msgpack-python#pypi-package-name

**Comment by souxun2015** [comment]
Thanks a lot, I found a lower version of msgpack. I uninstall it, and it works. but the speed is very slow, my computer has two 1080s.
`[0301 10:05:46 @graph.py:72] Running Op sync_variables/sync_variables_from_main_tower ...
[0301 10:05:46 @concurrency.py:38] Starting EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue ...
[0301 10:05:47 @base.py:255] Start Epoch 1 ...
  0%|          |0/5000[00:00<?,?it/s][0301 10:05:47 @input_source.py:496] Pre-filling StagingArea ...
[0301 10:05:51 @input_source.py:500] Successfully put 1 element to StagingArea.
  0%|          |12/5000[02:03<13:40:50, 0.10it/s]`

**Comment by souxun2015** [comment]
OK ,thank you.

**Comment by souxun2015** [comment]
I have test the code by the fake data, the speed can reach 5.99 it/s. However, it is only 0.53 it/s using the ILSVRC12. And in this case, i set 'ds = dataset.ILSVRC12(datadir, name, shuffle=False)'.
It makes full use of CPU, but the util of GPU is 0.

I  use imagenet-resnet.py without changing.

**Comment by ppwwyyxx** [comment]
Please be more clear about what you've done. What is 0.53it/s? Is it the speed of data or the speed of training? By saying you "set" a line of code, what exactly is happening to your code?

**Comment by ppwwyyxx** [comment]
Anyway, since fake data is faster than true data, your hardware is probably not fast enough to run the given dataflow and the tutorials have the information on how to benchmark and improve dataflow.

**Comment by souxun2015** [comment]
The training speed.
'ds = dataset.ILSVRC12(datadir, name, shuffle=False)'.
When shuffle = False, the result is the following:
`[0301 12:56:30 @concurrency.py:38] Starting EnqueueThread QueueInput/input_queue ...
[0301 12:56:30 @graph.py:72] Running Op sync_variables/sync_variables_from_main_tower ...
[0301 12:56:31 @concurrency.py:38] Starting EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue ...
[0301 12:56:31 @base.py:255] Start Epoch 1 ...
  0%|          |0/5000[00:00<?,?it/s][0301 12:56:31 @input_source.py:496] Pre-filling StagingArea ...
[0301 12:56:32 @input_source.py:500] Successfully put 1 element to StagingArea.
  1%|1         |66/5000[01:56<2:50:12, 0.48it/s]`

'ds = dataset.ILSVRC12(datadir, name, shuffle=True)'.
When shuffle = True, the result is the following:
`[0301 12:59:26 @concurrency.py:38] Starting EnqueueThread QueueInput/input_queue ...
[0301 12:59:26 @graph.py:72] Running Op sync_variables/sync_variables_from_main_tower ...
[0301 12:59:27 @concurrency.py:38] Starting EnqueueThread DataParallelInferenceRunner/QueueInput/input_queue ...
[0301 12:59:27 @base.py:255] Start Epoch 1 ...
  0%|          |0/5000[00:00<?,?it/s][0301 12:59:27 @input_source.py:496] Pre-filling StagingArea ...
[0301 12:59:29 @input_source.py:500] Successfully put 1 element to StagingArea.
  0%|          |10/5000[01:06<8:40:35, 0.16it/s]`

Shuffle will cost more time, I can understand this situation. But the speed is too slow. This is my computer information.
![image](https://user-images.githubusercontent.com/12790408/36827848-fd1185b4-1d50-11e8-91e0-946c49b7af6a.png)
The imagenet dataset is saved in HDD disk.
