### ISSUE TITLE
Transform the tensorflow trained model file to npz file error

### ISSUE THREAD

**Issue by sharpstill** [ppwwyyxx/tensorpack#688]
python version anaconda3.6 
tensorflow version 1.6.0 CPU version
I want to transform the following mobilenet pretrained model file to npz loadable file
http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz

After I unzip the compression file, I use following command :
`python tensorpack/scripts/dump-model-params.py --meta  ./mobilenet_v1_1.0_224.ckpt.meta  ./mobilenet_v1_1.0_224.ckpt.data-00000-of-00001 ./mobilenet_v1_1.0_224.npy`

It report error and I failed:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorpack/scripts/dump-model-params.py", line 25, in <module>
    sess.run(tf.global_variables_initializer())
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'save/RestoreV2_442': Operation was explicitly assigned to /job:ps/task:4/device:CPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: save/RestoreV2_442 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/task:4/device:CPU:0"](save/Const, save/RestoreV2_442/tensor_names, save/RestoreV2_442/shape_and_slices)]]

Caused by op 'save/RestoreV2_442', defined at:
  File "tensorpack/scripts/dump-model-params.py", line 20, in <module>
    tf.train.import_meta_graph(args.meta)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1909, in import_meta_graph
    **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 737, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'save/RestoreV2_442': Operation was explicitly assigned to /job:ps/task:4/device:CPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: save/RestoreV2_442 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/task:4/device:CPU:0"](save/Const, save/RestoreV2_442/tensor_names, save/RestoreV2_442/shape_and_slices)]]
```

**Comment by sharpstill** [comment]
It is tensorflow official model file, so it is should not have problem file

**Comment by sharpstill** [comment]
I found the solution in https://github.com/openai/pixel-cnn/issues/9

**Comment by sharpstill** [comment]
tf.train.import_meta_graph(args.meta, clear_devices=True)

**Comment by ppwwyyxx** [comment]
The script was not expected to work for other checkpoints, but you're right this is the solution.

**Comment by tingxingdong** [comment]
I want to do the reverse, from *npz to *ckpt. @sharpstill , Do you know is there any tool?

**Comment by ppwwyyxx** [comment]
https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.varmanip.save_chkpt_vars

```python
save_chkpt_vars(np.load("a.npz"), "a.ckpt")
```
