### ISSUE TITLE
Error: Cannot convert train2017.zip to an lmdb 

### ISSUE THREAD

**Issue by KindleHe** [ppwwyyxx/tensorpack#708]
When run `python data_sampler.py --lmdb train20117.lmdb --input train2017.zip --create` , fail and return the error.
```
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "data_sampler.py", line 111, in <module>
    dftools.dump_dataflow_to_lmdb(ds, args.lmdb)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack-0.8.3-py3.5.egg/tensorpack/utils/develop.py", line 51, in _dummy
    raise ImportError("Cannot import '{}', therefore '{}' is not available".format(dependency, func))
ImportError: Cannot import 'l,m,d,b', therefore 'dump_dataflow_to_lmdb' is not available
```

**Comment by ppwwyyxx** [comment]
The error message is a bit confusing, but it's saying you didn't install lmdb.

**Comment by KindleHe** [comment]
@ppwwyyxx Yes, I did not get the reason yet. Could you please give me some advice?

**Comment by ppwwyyxx** [comment]
Advice would be to install lmdb.
`pip install lmdb`.
