### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by dhingratul** [ppwwyyxx/tensorpack#709]
Assertion Error

1. Trying to replicate the experiment from here, https://github.com/czhu95/ternarynet
2. a. NameError: name 'StatPrinter' is not defined
2 b. Commenting the StatPrinter() callback gives the following error

`Traceback (most recent call last):
  File "./tw-cifar10-resnet.py", line 213, in <module>
    config = get_config(args.n)
  File "./tw-cifar10-resnet.py", line 199, in get_config
    max_epoch=400,
  File "/home/username/.local/lib/python3.6/site-packages/tensorpack/train/config.py", line 111, in __init__
    assert_type(callbacks, list)
  File "/home/username/.local/lib/python3.6/site-packages/tensorpack/train/config.py", line 95, in assert_type
    assert isinstance(v, tp), v.__class__
AssertionError: <class 'tensorpack.callbacks.group.Callbacks'>
`
4. Your environment:
	+ Python version. 3.6
	+ TF version: 1.6
	+ Tensorpack version:0.8.5

**Comment by ppwwyyxx** [comment]
The `ternarynet` project used very old tensorpack and tensorflow that are not compatible with what they are now. It has actually included a version of tensorpack in its repo. It's not expected to work with latest tensorpack.

**Comment by ppwwyyxx** [comment]
FYI I've included the implementation of `Trained Ternary Quantization` paper inside tensorpack examples now: https://github.com/ppwwyyxx/tensorpack/tree/master/examples/DoReFa-Net
