### ISSUE TITLE
How to run Fast RCNN on Windows?

### ISSUE THREAD

**Issue by Superlee506** [ppwwyyxx/tensorpack#723]
Hi, yx:
I'm new to Tensorpack,  as I know "PrefetchDataZMQ" doesn't support for windows, so I change it with "PrefetchData" when I run the Fast RCNN example. However the following errors occurs.
My environment:
    Win10 x64
    Python: 3.5.3
    TF version: 1.4.0
    Tensorpack version: 0.8.5
Do I miss anything when I change it to run on Windows?
"
Traceback (most recent call last):
  File "D:/Github/Tensorpack_Examples/FasterRCNN/train.py", line 383, in <module>
    data=QueueInput(get_train_dataflow(add_mask=config.MODE_MASK)),
  File "D:\Github\Tensorpack_Examples\FasterRCNN\data.py", line 273, in get_train_dataflow
    ds = PrefetchData(ds,500,1)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\dataflow\parallel.py", line 185, in __init__
    start_proc_mask_signal(self.procs)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\utils\concurrency.py", line 212, in start_proc_mask_signal
    p.start()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_train_dataflow.<locals>.preprocess'
D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input
"

**Comment by ppwwyyxx** [comment]
`PrefetchData` probably does not support windows either. You can just remove it and expect a minor slow down in speed.

**Comment by Superlee506** [comment]
@ppwwyyxx Thanks for your timely reply. I remove the prefetch method as you say, but still have the following errors. Do I need to change the trainer method at the same time?


"Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\train\base.py", line 256, in main_loop
    self._callbacks.before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\base.py", line 63, in before_train
    self._before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\group.py", line 70, in _before_train
    cb.before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\base.py", line 63, in before_train
    self._before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\prof.py", line 60, in _before_train
    start_proc_mask_signal(self._proc)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\utils\concurrency.py", line 212, in start_proc_mask_signal
    p.start()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\group.py", line 76, in _after_train
    cb.after_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\base.py", line 171, in after_train
    self._after_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\prof.py", line 80, in _after_train
    self._proc.join()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\process.py", line 120, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
Traceback (most recent call last):
  File "D:/Github/Tensorpack_Examples/FasterRCNN/train.py", line 401, in <module>
    launch_train_with_config(cfg, trainer)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\train\interface.py", line 91, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\train\base.py", line 331, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\train\base.py", line 303, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\utils\argtools.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\train\base.py", line 256, in main_loop
    self._callbacks.before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\base.py", line 63, in before_train
    self._before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\group.py", line 70, in _before_train
    cb.before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\base.py", line 63, in before_train
    self._before_train()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\callbacks\prof.py", line 60, in _before_train
    start_proc_mask_signal(self._proc)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\tensorpack\utils\concurrency.py", line 212, in start_proc_mask_signal
    p.start()
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed
[0405 16:54:43 @input_source.py:149] EnqueueThread QueueInput/input_queue Exited.
D:\ProgramData\Anaconda3\envs\py35\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "D:\ProgramData\Anaconda3\envs\py35\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input
"

**Comment by ppwwyyxx** [comment]
You need to remove `GPUUtilizationTracker` from the callbacks. Looks like it does not support windows either.

**Comment by Superlee506** [comment]
@ppwwyyxx It works, thanks for your patience.  It has higher GPU utilization than Keras. I think keras can really play for fun and f I should abandon keras from now on and . Thanks again.

**Comment by ppwwyyxx** [comment]
Regarding the original issue, turned out that PrefetchData does support windows, but windows has a more strict picklability requirement for processes, i.e. it requires to pickle `get_train_dataflow.preprocess`. Ref: https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods
