### ISSUE TITLE
Error when running MaskRCNN predict

### ISSUE THREAD

**Issue by pimpke** [ppwwyyxx/tensorpack#727]
Hi, I'm having some trouble running MaskRCNN's predict using the following command (on a GPU without any code changes):

`python tensorpack/examples/FasterRCNN/train.py --predict 'images.jpg' --load 'COCO-ResNet50-MaskRCNN.npz' --datadir 'coco'`

The model weights were downloaded from http://models.tensorpack.com/

The error I get:
> Traceback (most recent call last):
>   File "tensorpack/examples/FasterRCNN/train.py", line 354, in <module>
>     output_names=get_model_output_names()))
>   File "tensorpack/tensorpack/predict/base.py", line 170, in __init__
>     config.session_init._run_init(sess)
>   File "tensorpack/tensorpack/tfutils/sessinit.py", line 220, in _run_init
>     upd.update({name: value for name, value in six.iteritems(self._prms) if name in intersect})
>   File "tensorpack/tensorpack/tfutils/varmanip.py", line 118, in update
>     SessionUpdate.load_value_to_var(v, value)
>   File "tensorpack/tensorpack/tfutils/varmanip.py", line 71, in load_value_to_var
>     "{}: {}!={}".format(name, varshape, val.shape)
> AssertionError: group3/block0/convshortcut/W: (1, 1, 27, 2048)!=(1, 1, 1024, 2048)

All the mismatched weights shapes:
> conv0/W:0 (7, 7, 8, 64) (7, 7, 3, 64)
> group3/block0/conv1/W:0 (1, 1, 28, 512) (1, 1, 1024, 512)
> group3/block0/convshortcut/W:0 (1, 1, 27, 2048) (1, 1, 1024, 2048)
> group1/block0/conv2/W:0 (3, 3, 129, 128) (3, 3, 128, 128)
> group2/block0/convshortcut/W:0 (1, 1, 511, 1024) (1, 1, 512, 1024)
> group0/block0/convshortcut/W:0 (1, 1, 65, 256) (1, 1, 64, 256)
> group3/block0/conv2/W:0 (3, 3, 513, 512) (3, 3, 512, 512)
> group2/block0/conv2/W:0 (3, 3, 257, 256) (3, 3, 256, 256)
> group1/block0/convshortcut/W:0 (1, 1, 255, 512) (1, 1, 256, 512)
> group0/block0/conv1/W:0 (1, 1, 65, 64) (1, 1, 64, 64)

I have also tried returning to maskrcnn branch a few months back and the issue persists.

My environment:
Python 3.5.2
TF version: v1.5.0-0-g37aa430d84 1.5.0
Tensorpack version: 0.7.1

**Comment by ppwwyyxx** [comment]
Please use latest tensorpack.

**Comment by pimpke** [comment]
I wrote a wrong version in the issue description, I actually used the latest version 0.8.5 when I was testing. Corrected.

**Comment by ppwwyyxx** [comment]
You give:
```
File "tensorpack/examples/FasterRCNN/train.py", line 354, in 
output_names=get_model_output_names()))
```
But line 354 in either master or 0.8.5, line 354 in train.py is not this:
https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/train.py#L354
https://github.com/ppwwyyxx/tensorpack/blob/0.8.5/examples/FasterRCNN/train.py#L354

**Comment by pimpke** [comment]
I forgot to update the error in the issue description when I returned to master from mask_rcnn branch. The error is the same on master (description updated).

Were there any recent changes to 'COCO-ResNet50-MaskRCNN.npz' on http://models.tensorpack.com, because I couldn't find a recent commit in the commit history that works?

**Comment by ppwwyyxx** [comment]
There were no recent changes and all recent commits are supposed to work.
Can you post the entire log?

**Comment by ppwwyyxx** [comment]
Is there still an error?
