### ISSUE TITLE
  Excuse me, which version of tensorpack do you need for your source code "Stereo-Pose-Machines"?

### ISSUE THREAD

**Issue by TKZC0615** [ppwwyyxx/tensorpack#729]
Excuse me, In the near future, I was learning your **"Stereo-Pose-Machines"** source code, built the environment on **Ubuntu16.04**, fitted part of the code and successfully tested the part of "Test Cameras", "Calibrate Cameras", "Test 3D Visualization is working". **Besides, I can run the program of CPM in the example of tensorpack.** But when running **"Test CPM is working"** code, there are some errors related to "tensorpack". At present, I have modified some of the errors brought by some version updates, such as "ParamRestore was renamed to DictRestore". **But there are still some mistakes.** 

So, I'd like to ask you the following **questions**:

1. How to get the "cpm.npy" file? I can get "cpm.npz" at the moment. Recently, I have just learned, please forgive me.
2. what is the tensorpack version you used to run the code of "Test CPM is working" in "Stereo-Pose-Machines" successfully?

Look forward to your reply, thank you!

**PS: output is as follows:** 
```
"Traceback (most recent call last):"
File "/home/robot/software/sourceCode_install/pycharm-community-2018.1/helpers/pydev/pydevd.py", line 1664, in <module>.
(main)
File "/home/robot/software/sourceCode_install/pycharm-community-2018.1/helpers/pydev/pydevd.py", line 1658, in main.
Globals = debugger.run (setup['file'], None, None, is_module).
File "/home/robot/software/sourceCode_install/pycharm-community-2018.1/helpers/pydev/pydevd.py", line 1068, in run.
Pydev_imports.execfile (file, globals, locals) # execute the script
File "/home/robot/Desktop/project/Pycharm/Stereo-Pose-Machines/src/main.py", line 178, in <module>.
Stereo_cpm_viewer (CPM) function # stereo test algorithm
File "/home/robot/Desktop/project/Pycharm/Stereo-Pose-Machines/src/main.py", line 39, in stereo_cpm_viewer.
Runner = get_parallel_runner ('../data/cpm.npy')
File "/home/robot/Desktop/project/Pycharm/Stereo-Pose-Machines/src/runner.py", line 70, in get_parallel_runner.
Output_names=['resized_map']
File "/home/robot/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/tensorpack/predict/config.py", line 58, in __init__.
Self.inputs_desc = model.get_inputs_desc ()
File "/home/robot/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/functools32/functools32.py", line 378, in wrapper.
Result = user_function (*args, **kwds)
File "/home/robot/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 106, in get_inputs_desc.
Inputs = self.inputs ()
File "/home/robot/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 126, in inputs.
Raise NotImplementedError ()
NotImplementedError "
```

**Comment by ppwwyyxx** [comment]
Not a tensorpack question, so closing.
Stereo-Pose-Machines is not maintained any more as mentioned in its readme. The code is there for a reference if anyone is interested in studying such projects but this means people will need to figure out the code by themselves. It requires specific hardwares so it's not meant for anyone to actually run. 
It is developed around Dec 2016 with tensorpack version at that time. The error you saw is due to an API change half a year ago, which can probably be fixed in https://github.com/ppwwyyxx/Stereo-Pose-Machines/commit/cadb5d057f224e5d53d17c33e776b5296ca7eccf,  following [tensorpack changelog](https://github.com/ppwwyyxx/tensorpack/blob/master/CHANGES.md).
cpm.npy was the model we trained for that project that is not available now.

**Comment by TKZC0615** [comment]
OK. Thank you very much for your reply.
