### ISSUE TITLE
Is the operation error of this function "DataParallelOfflinePredictor" caused by the revision?

### ISSUE THREAD

**Issue by TKZC0615** [ppwwyyxx/tensorpack#730]
Hello, I have a error when I run the **DataParallelOfflinePredictor** function. After debugging, I am puzzled by the following statements **if any(k in name for k in [':', '/', ' '])**.

The statement
 `inputs_desc = [InputDesc(desc.type, desc.shape, tower_name + '/' + desc.name)
for desc in config.inputs_desc]` 
in this function adds the "/", but the function  **__new__(cls, type, shape, name)** in the class of **InputDesc**  will report error when it detects "/" in the statement 
`if any(k in name for k in [':', '/', ' ']):
            raise ValueError("Invalid InputDesc name: '{}'".format(name)).` 

No example of calling this function was found in the latest version, an I don't know if my idea is right or not.

**ps: The output is as follows:**

> Traceback (most recent call last):
  File "/home/robot/software/sourceCode_install/pycharm-community-2018.1/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/robot/software/sourceCode_install/pycharm-community-2018.1/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/robot/software/sourceCode_install/pycharm-community-2018.1/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/robot/Desktop/project/Pycharm/Stereo-Pose-Machines/src/main.py", line 178, in <module>
    stereo_cpm_viewer()
  File "/home/robot/Desktop/project/Pycharm/Stereo-Pose-Machines/src/main.py", line 39, in stereo_cpm_viewer
    runner = get_parallel_runner('../data/cpm.npy')
  File "/home/robot/Desktop/project/Pycharm/Stereo-Pose-Machines/src/runner.py", line 72, in get_parallel_runner
    predictor = DataParallelOfflinePredictor(cfg, [0,1])
  File "/home/robot/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/tensorpack/predict/multigpu.py", line 99, in __init__
    for desc in config.inputs_desc]
  File "/home/robot/anaconda3/envs/caffe-tf/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 38, in __new__
    raise ValueError("Invalid InputDesc name: '{}'".format(name))
ValueError: Invalid InputDesc name: 'tower0/input'

Thank you.

**Comment by ppwwyyxx** [comment]
Interesting, that's indeed a problem. It's just `DataParallelOfflinePredictor` was never useful (it's not fast) so I wasn't thinking about it.
