### ISSUE TITLE
humanize_time_delta cause training stop

### ISSUE THREAD

**Issue by AlphaXiao** [ppwwyyxx/tensorpack#741]
calling Stack:

Traceback (most recent call last):
  File "src/main.py", line 95, in <module>
    launch_train_with_config(config, SimpleTrainer())
  File "/Users/tensorpack/train/interface.py", line 91, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/Users/tensorpack/train/base.py", line 331, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/Users/tensorpack/train/base.py", line 303, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/Users/tensorpack/utils/argtools.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/Users/tensorpack/train/base.py", line 272, in main_loop
    self.loop.epoch_num, self.loop.global_step, humanize_time_delta(time.time() - start_time)))
  File "/Users/tensorpack/utils/utils.py", line 44, in humanize_time_delta
    assert sec >= 0, sec
AssertionError: -0.237720012665

The training time of one epoch is calculated based on time.time().
According to [python doc](https://docs.python.org/2/library/time.html#time.time), time.time() may return a lower value than a previous call if the system clock has been set back between the two calls. 

So when training is very fast, Trainer.main_loop may give a negative parameter to utility function humanize_time_delta, which cause the assertion fail in this function. Thus cause train stop.

Suggest giving a warn in humanize_time_delta rather than assert.

**Comment by ppwwyyxx** [comment]
Interesting. Thanks for the report!
