### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Minotaur-CN** [ppwwyyxx/tensorpack#743]
1. Unexpected Problems / Potential Bugs

Dear ppwwyyx,
The error occured when re-train the model or using ctrl-c to interupt the training precedure. It seems the threaded were not killed using ctrl-c interuption.

========

0221 07:44:38 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Traceback (most recent call last):
  File "./src/train.py", line 71, in <module>
    df = get_dataflow_batch(args.datapath, True, args.batchsize, img_path=args.imgpath)
  File "/home/test/Project/2018-05-02//src/pose_dataset.py", line 388, in get_dataflow_batch
    ds = get_dataflow(path, is_train, img_path=img_path)
  File "/home/test/Project/2018-05-02//src/pose_dataset.py", line 367, in get_dataflow
    ds = PrefetchData(ds, 1000, multiprocessing.cpu_count() * 4)
##   **File "/home/test/anaconda3/lib/python3.5/site-packages/tensorpack-0.8.5-py3.5.egg/tensorpack/dataflow/parallel.py", line 185, in __init__ start_proc_mask_signal(self.procs)**
  File "/home/test/anaconda3/lib/python3.5/site-packages/tensorpack-0.8.5-py3.5.egg/tensorpack/utils/concurrency.py", line 212, in start_proc_mask_signal
    p.start()
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
## **BlockingIOError: [Errno 11] Resource temporarily unavailable Process _Worker-103:**

Traceback (most recent call last):
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/test/anaconda3/lib/python3.5/site-packages/tensorpack-0.8.5-py3.5.egg/tensorpack/dataflow/parallel.py", line 160, in run
    self.queue.put(dp)
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/queues.py", line 87, in put
    self._start_thread()
  File "/home/test/anaconda3/lib/python3.5/multiprocessing/queues.py", line 169, in _start_thread
    self._thread.start()
  File "/home/test/anaconda3/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())

**Comment by ppwwyyxx** [comment]
> The error occured when re-train the model or using ctrl-c to interupt the training precedure
I don't understand what do you mean by the "or". What exactly did you do to see this log?

**Comment by Minotaur-CN** [comment]
1 . What will happen if you don't press ctrl-c ?
Run normal, no error happends.


2. What will happen if you press ctrl-c a lot of times?
Change LearningRate or want to re-training another model, using ctrl-c to interupt previous trainning code. Can not start the training precedure again, must kill the tensorpack thread by command.

**Comment by ppwwyyxx** [comment]
What will happen if you press ctrl-c a lot of times? --- Does this give you back to the command line or not?

And by saying "Can not start the training precedure again" what exactly did you observe? Does this give the error you've posted above or something else? Could you post the error?

**Comment by Minotaur-CN** [comment]
1. press ctrl-c can quit training process as normal. 
2. all error just as I posted before.  Using linux bash 'top', could see the training thread are not terminated, had to kill the thread by command
kill `ps -ef|grep python | grep -v grep|awk '{print $2}'`

**Comment by ppwwyyxx** [comment]
OK now I understand. This is related to issue #668 and can probably be solved in the master branch if you've installed the "python-prctl" package.

**Comment by Minotaur-CN** [comment]
cool.
Thanks for your reply!
