### ISSUE TITLE
No OpKernel was registered to support Op 'NcclAllReduce' with these attrs

### ISSUE THREAD

**Issue by samson-wang** [ppwwyyxx/tensorpack#759]
I run the command as following
`python imagenet-resnet.py --batch 256 -d 50 --data ~/data/imagenet/ILSVRC/Data/CLS-LOC/`

```
Traceback (most recent call last):
  File "imagenet-resnet.py", line 148, in <module>
    launch_train_with_config(config, trainer)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/train/base.py", line 330, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/train/base.py", line 301, in train
    self.initialize(session_creator, session_init)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/train/base.py", line 229, in initialize
    self.sess = session_creator.create_session()
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 467, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 285, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: AllReduceGrads/NcclAllReduce_639 = NcclAllReduce[T=DT_FLOAT, num_devices=4, reduction="sum", shared_name="c159", _device="/device:GPU:3"](tower3/gradients/AddN)]]

Caused by op u'AllReduceGrads/NcclAllReduce_639', defined at:
  File "imagenet-resnet.py", line 148, in <module>
    launch_train_with_config(config, trainer)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/train/interface.py", line 81, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/train/tower.py", line 178, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/train/trainers.py", line 166, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 230, in build
    all_grads = allreduce_grads(all_grads, average=self._average)  # #gpu x #param
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/tfutils/scope_utils.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorpack/graph_builder/utils.py", line 140, in allreduce_grads
    summed = nccl.all_sum(grads)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 47, in all_sum
    return _apply_all_reduce('sum', tensors)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 228, in _apply_all_reduce
    shared_name=shared_name))
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/contrib/nccl/ops/gen_nccl_ops.py", line 59, in nccl_all_reduce
    num_devices=num_devices, shared_name=shared_name, name=name)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/samson/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'NcclAllReduce' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: AllReduceGrads/NcclAllReduce_639 = NcclAllReduce[T=DT_FLOAT, num_devices=4, reduction="sum", shared_name="c159", _device="/device:GPU:3"](tower3/gradients/AddN)]]
```
TF version :
`('v1.8.0-0-g93bc2e2072', '1.8.0')`

And the tensorpack is updated.
`0.8.5`

**Comment by ppwwyyxx** [comment]
Some possibilities: your TF does not support GPU. Your GPU was occupied or has other errors.

**Comment by samson-wang** [comment]
It's weird. Pytorch and Caffe2 works well.
The TF was installed through pip. I will try to compile from source.

**Comment by ppwwyyxx** [comment]
Did you install tensorflow or tensorflow-gpu from pip?

**Comment by ppwwyyxx** [comment]
That's the problem

**Comment by samson-wang** [comment]
Any suggestions?

**Comment by ppwwyyxx** [comment]
...uninstall it and install tensorflow-gpu

**Comment by samson-wang** [comment]
Another thing.
I have tried to train imagenet on caffe2/caffe/pytorch. And never get close to the reported accuracy. The learning curve is different.
I can only get 72% top 1 accuracy. The `inception-style` data augmentation is used. I only have 4 titanX, so I adjusted the learning rate according to the `linear scaling rule`. No help either.

The tensorpack seems to be the chance. Hope it works great.

**Comment by ChaoWangHS** [comment]
I meet the same thing too.

python 2.7 
tensorflow 1.7.0 by `pip install tensorflow==1.7.0`
install tensorpack using `pip install tensorpack`

**Comment by ppwwyyxx** [comment]
...uninstall it and install tensorflow-gpu

**Comment by CharlesHua** [comment]
Have you solved this problem? I meet a same one.

**Comment by ianferreira** [comment]
2020-01-26 18:04:02.457549: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-01-26 18:04:07.434753: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll

...
l GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:0a:00.0, compute capability: 6.1)
2020-01-26 18:04:10.446438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:1 with 6382 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1070, pci bus id: 0000:0b:00.0, compute capability: 6.1)
2020-01-26 18:04:10.453885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:2 with 6382 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1070, pci bus id: 0000:43:00.0, compute capability: 6.1)
2020-01-26 18:04:10.460182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:3 with 6382 MB memory) -> physical GPU (device: 3, name: GeForce GTX 1070, pci bus id: 0000:44:00.0, compute capability: 6.1)
2020-01-26 18:04:21.053155: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
2020-01-26 18:04:21.109841: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cupti64_100.dll
2020-01-26 18:04:21.392770: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 0 kernel records, 1 memcpy records.

InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node Adam/NcclAllReduce}}with these attrs: [reduction="sum", shared_name="c1", T=DT_FLOAT, num_devices=4]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

	 [[Adam/NcclAllReduce]] [Op:__inference_distributed_function_3448]

**Comment by githubpiyush** [comment]
I have got similar error, you can see it below:
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MutableDenseHashTableV2' used by node MutableDenseHashTable (defined at /Desktop/temp2/model/model.py:166) with these attrs: [value_dtype=DT_STRING, max_load_factor=0.8, initial_num_buckets=131072, shared_name="", use_node_name_sharing=true, key_dtype=DT_INT64, container="", value_shape=[]]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_INT64]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_DOUBLE]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_BOOL]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_VARIANT]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_INT64]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_DOUBLE]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_BOOL]
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_DOUBLE]

	 [[MutableDenseHashTable]]
Note: The error line is where i used deleted key = -1 indside this function tf.lookup.experimental.DenseHashTable
