### ISSUE TITLE
I try to implement cifar10-resnet.py from tensorpack-examples-ResNet on windows 10

### ISSUE THREAD

**Issue by Jarlan1207** [ppwwyyxx/tensorpack#762]
[0514 20:52:37 @logger.py:109] WRN Log directory train_log\cifar10-resnet exists! Use 'd' to delete it. 
[0514 20:52:37 @logger.py:112] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):k
[0514 20:52:52 @logger.py:67] Existing log file 'train_log\cifar10-resnet\log.log' backuped to 'train_log\cifar10-resnet\log.log.0514-205252'
[0514 20:52:52 @logger.py:74] Argv: C:/Users/Jarlan/PycharmProjects/tensorpack-master/examples/ResNet/cifar10-resnet.py
[0514 20:52:52 @fs.py:88] WRN Env var $TENSORPACK_DATASET not set, using C:\Users\Jarlan\tensorpack_data for datasets.
[0514 20:52:52 @cifar.py:32] Found cifar10 data in C:\Users\Jarlan\tensorpack_data\cifar10_data.
[0514 20:52:53 @parallel.py:175] WRN MultiProcessPrefetchData does support windows. However, windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0514 20:52:53 @parallel.py:185] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Traceback (most recent call last):
  File "C:/Users/Jarlan/PycharmProjects/tensorpack-master/examples/ResNet/cifar10-resnet.py", line 157, in <module>
    dataset_train = get_data('train')
  File "C:/Users/Jarlan/PycharmProjects/tensorpack-master/examples/ResNet/cifar10-resnet.py", line 138, in get_data
    ds = PrefetchData(ds, 3, 2)
  File "C:\Users\Jarlan\PycharmProjects\tensorpack-master\tensorpack\dataflow\parallel.py", line 192, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\Users\Jarlan\PycharmProjects\tensorpack-master\tensorpack\utils\concurrency.py", line 229, in start_proc_mask_signal
    p.start()
  File "F:\Anaconda\envs\py3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "F:\Anaconda\envs\py3\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\Anaconda\envs\py3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "F:\Anaconda\envs\py3\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\Anaconda\envs\py3\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_data.<locals>.<lambda>'

I don't know what's going wrong. I am running it on windows 10

**Comment by Jarlan1207** [comment]
Could you help me ?

**Comment by ppwwyyxx** [comment]
It's already printed out:
```
[0514 20:52:53 @parallel.py:175] WRN MultiProcessPrefetchData does support windows. However, windows requires more strict picklability on processes, which may lead of failure on some of the code.
```

**Comment by Jarlan1207** [comment]
So, should I use Ubuntu to run it?

**Comment by ppwwyyxx** [comment]
Or you can remove `PrefetchData` from your `get_data` function.

**Comment by Jarlan1207** [comment]
Ok, I got it, Thank you

**Comment by ppwwyyxx** [comment]
I found the reason is that on windows, expressions like:
```python
            imgaug.MapImage(lambda x: x - pp_mean),
```
cannot be used with multiprocessing (the lambda is not pickleable).

An alternative fix is to define a function at global scope that does the subtraction. Then use 
```python
imgaug.MapImage(func)
```
instead.
