### ISSUE TITLE
I try to implement cifar10-resnet.py from tensorpack-examples-ResNet on Ubuntu

### ISSUE THREAD

**Issue by Jarlan1207** [ppwwyyxx/tensorpack#770]
/home/jarlan/anaconda3/bin/python3.5 /home/jarlan/PycharmProjects/tensorflow/examples/ResNet/cifar10-resnet.py
[0520 15:50:33 @logger.py:109] WRN Log directory train_log/cifar10-resnet exists! Use 'd' to delete it. 
[0520 15:50:33 @logger.py:112] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):k
[0520 15:50:37 @logger.py:67] Existing log file 'train_log/cifar10-resnet/log.log' backuped to 'train_log/cifar10-resnet/log.log.0520-155037'
[0520 15:50:37 @logger.py:74] Argv: /home/jarlan/PycharmProjects/tensorflow/examples/ResNet/cifar10-resnet.py
[0520 15:50:37 @fs.py:88] WRN Env var $TENSORPACK_DATASET not set, using /home/jarlan/tensorpack_data for datasets.
[0520 15:50:37 @cifar.py:32] Found cifar10 data in /home/jarlan/tensorpack_data/cifar10_data.
[0520 15:50:38 @parallel.py:185] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0520 15:50:38 @cifar.py:32] Found cifar10 data in /home/jarlan/tensorpack_data/cifar10_data.
[0520 15:50:39 @gpu.py:39] WRN Found nvidia-smi. But TensorFlow was not built with CUDA support!
[0520 15:50:39 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0520 15:50:39 @input_source.py:193] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0520 15:50:39 @training.py:103] Building graph for training tower 0 ...
Traceback (most recent call last):
  File "/home/jarlan/PycharmProjects/tensorflow/examples/ResNet/cifar10-resnet.py", line 175, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_gpu))
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/train/interface.py", line 81, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/train/tower.py", line 178, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/train/trainers.py", line 91, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/graph_builder/training.py", line 151, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/graph_builder/training.py", line 108, in build_on_towers
    ret.append(func())
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/train/tower.py", line 205, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/tfutils/tower.py", line 209, in __call__
    output = self._tower_fn(*args)
  File "/home/jarlan/PycharmProjects/tensorflow/tensorpack/graph_builder/model_desc.py", line 235, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "/home/jarlan/PycharmProjects/tensorflow/examples/ResNet/cifar10-resnet.py", line 50, in build_graph
    assert tf.test.is_gpu_available()
AssertionError

Process finished with exit code 1

I am new to it. I don't know what's going wrong. Could you help me ?

**Comment by ChaoWangHS** [comment]
May you run it on a CPU not using GPU.

**Comment by Jarlan1207** [comment]
I run it on  tensorflow-gpu

**Comment by Jarlan1207** [comment]
i run these code

import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

Then I  got 

2018-05-20 17:45:16.481366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-05-20 17:45:16.481375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
2018-05-20 17:45:16.482564: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 133.81M (140312576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-05-20 17:45:16.484438: I tensorflow/core/common_runtime/direct_session.cc:265] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0
PyDev console: starting.
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux

Isn't  tensorflow-gpu

**Comment by ppwwyyxx** [comment]
Your log said `assert tf.test.is_gpu_available()` failed.

**Comment by Jarlan1207** [comment]
Thank you. I run it on tensorflow-gpu-1.3. and now the problem was solved.
