### ISSUE TITLE
MNIST-convnet is not working -- 'dataset' is not defined

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#84]
Commit c3f5307eb96a0efb313f4b4bbff5da18b1d80119 introduces a bug, 

````
[0102 11:45:47 @logger.py:57] Argv: mnist-convnet.py
Traceback (most recent call last):
  File "mnist-convnet.py", line 134, in <module>
    config = get_config()
  File "mnist-convnet.py", line 95, in get_config
    dataset_train, dataset_test = get_data()
  File "mnist-convnet.py", line 87, in get_data
    train = BatchData(dataset.Mnist('train'), 128)
NameError: global name 'dataset' is not defined

````

But 9c42c84fa682ba34110e1e0441ad84290f8e7b7b works fine.

It seems that this new commit expect
````python
dataflow.dataset.MNIST
````
instead of
````python
dataset.MNIST
````

Is this intended? Then each example using these datasets needs an update.

**Comment by ppwwyyxx** [comment]
I was making changes on import and introduced a bug.
