### ISSUE TITLE
symbolic_functions is not defined

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#92]
````
~/tmp/tensorpack/examples (master) $ python mnist-convnet.py 

Traceback (most recent call last):
  File "mnist-convnet.py", line 168, in <module>
    SimpleTrainer(config).train()
  File "/home/wieschol/git/tensorpack/tensorpack/train/base.py", line 58, in train
    self.setup()
  File "/home/wieschol/git/tensorpack/tensorpack/train/base.py", line 126, in setup
    self._setup()
  File "/home/wieschol/git/tensorpack/tensorpack/train/trainer.py", line 83, in _setup
    model.build_graph(self.input_vars)
  File "/home/wieschol/git/tensorpack/tensorpack/models/model_desc.py", line 108, in build_graph
    self._build_graph(model_inputs)
  File "mnist-convnet.py", line 87, in _build_graph
    wrong = symbolic_functions.prediction_incorrect(logits, label, name='incorrect')
NameError: global name 'symbolic_functions' is not defined
````

possible bugfix
[bugfix.txt](https://github.com/ppwwyyxx/tensorpack/files/690768/bugfix.txt)

edit: same for `summary`

**Comment by PatWie** [comment]
Possible patch

````git
From e8f77a7918eada5505a92d89d4b8476f0257eb23 Mon Sep 17 00:00:00 2001
From: PatWie <patrick@wieschollek.info>
Date: Fri, 6 Jan 2017 21:27:04 +0100
Subject: [PATCH] fix

---
 tensorpack/tfutils/__init__.py | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

diff --git a/tensorpack/tfutils/__init__.py b/tensorpack/tfutils/__init__.py
index f75d947..57fbb11 100644
--- a/tensorpack/tfutils/__init__.py
+++ b/tensorpack/tfutils/__init__.py
@@ -9,6 +9,7 @@ __all__ = []
 
 
 def _global_import(name):
+    __all__.append(name)
     p = __import__(name, globals(), None, level=1)
     lst = p.__all__ if '__all__' in dir(p) else dir(p)
     for k in lst:
@@ -21,12 +22,13 @@ _TO_IMPORT = set([
     'common',
     'gradproc',
     'argscope',
-    'tower'
+    'tower',
+    'symbolic_functions',
+    'summary'
     ])
 
 _CURR_DIR = os.path.dirname(__file__)
-for _, module_name, _ in walk_packages(
-        [_CURR_DIR]):
+for _, module_name, _ in walk_packages([_CURR_DIR]):
     srcpath = os.path.join(_CURR_DIR, module_name + '.py')
     if not os.path.isfile(srcpath):
         continue
-- 
2.7.4
````

**Comment by ppwwyyxx** [comment]
I started to use __all__ for all module to work with sphinx api doc. This was causing some problems with import.
